essen = [
    "einen Wirsingeintopf",
    "einen Lahmacun",
    "eine Portion Kartoffelbrei",
    "Spinat",
    "eine Brezel",
    "einen Seitan Döner",
    "einen Teller Spaghetti Bolognese",
    "einen Teller Spaghetti mit Käsesahnesoße",
    "einen Obstteller",
    "zwei Käsebrote",
    "Okonomiyaki",
    "zwei Stück Erdbeertorte",
    "feuriges Chili sin Carne",
    "ein fluffiges Rührei",
    "eine leckere Pizza",
    "einen frischen Gurkensalat",
    "einen großen Chefsalat",
    "Schwarzwurzel und Kartoffelbrei",
    "ungarisches Gulasch",
    "Spaghetti mit Soja-Bolognese",
    "ein original französisches Ratatouille",
    "einen sahnigen Schokopudding",
    "arme Ritter",
    "Pommes mit Majo",
    "leckeren Kartoffelauflauf",
    "einen Toast Hawaii",
    "indisches Gemüse Curry",
    "einen Planted-Gyrosteller mit Tzatziki",
    "ein Pilz-Risotto",
    "ein paar Mini-Frühlingsrollen",
    "würziges Sauerkraut",
    "ein Schälchen Apfelmus",
    "Bratkartoffeln",
    "asiatisches Wokgemüse",
    "einen Teller mit süßem Milchreis",
    "eine Lasagne",
    "chinesisch gebratene Nudeln",
    "ein Tomaten-Baguette",
    "eine Mango",
    "eine Portion Falafel mit Hummus",
    "ein feuriges Chili con Soja",
    "einen Teller getrocknete Jackfruchtstücke",
    "einen Teller Spaghetti mit Gorgonzolasoße",
    "einen Big Vegan TS",
    "einen McPlant",
    "einen Teller voll Burritos",
    "eine Portion handgerolltes Sushi",
    "ein Butterbrot",
    "eine Schnittlauch-Brezel",
    "einen Teller szegediner Gulasch",
    "eine Portion Avocado Maki",
    "eine Portion Konjaklachs-Maki"
    "eine Spinatlasagne",
    "einen Teller vegetarisch gefüllte Paprika",
    "einen Teller gefüllte Zucchini",
    "ein Schinken-Käse-Omelett",
    "Chop Suey",
    "ein großes Stück Tofurducken",
    "einen Teller Spaghetti Aglio e Olio",
    "Nudeln mit Pesto",
    "einen Teller Paella",
    "einen Berg Pfannkuchen",
    "einen Teller Belgische Waffeln mit Schokosoße",
    "eine Waffel mit Puderzucker",
    "Grießbrei mit Amarena Kirschen",
    "einen Kaiserschmarrn mit Apfelmus",
    "Palatschinken mit Marillenmarmelade und Staubzucker",
    "eine Schale Grießbrei mit Nutella",
    "ein Gefäß mit Wan Tan",
    "frittierten Tofu auf Eierreis",
    "Kürbiskernbratlinge",
    "veganen Räucherspeck mit frischen Zwiebeln",
    "eine große Portion Tortellini mit Frischkäsefüllung",
    "ein rustikales Krustenbrot mit Bergkäse",
    "einen Eimer buntes Popcorn",
    "dampfenden Kaiserschmarrn",
    "Grießbrei mit roter Grütze",
    "brasilianischen Schwarzbohnen-Eintopf (feijoada)",
    "eine Portion Reispudding",
    "einen Teller selbstgedrehte Zucchini-Nudeln",
    "mildes Möhrenmischmasch",
    "gegrillten Kürbis",
    "knusprige Frühlingsrollen mit Dip",
    "drei frische Onigiri",
    "eine Schale Stachelbeerkompott",
    "entzückendes Erbsengemüse",
    "Eierlikörkuchen mit vollständig ausgebackenem Eierlikör",
    "Wassermelonensalat in einer ausgehöhlten Wassermelone",
    "einen runderneuerten Obstkuchen mit upgegradeten Erdbeeren",
    "sauer eingelegten Spargel in Aspik",
    "gedünsteten Brokkoli",
    "gebratenes Gemüse mit Erdnusssoße",
    "Quinoasalat mit feinen Tomaten",
    "einen italienischen Klassiker mit einem ~Spritzer~ Olivenöl",
    "ein selbst gebackenes Kürbiskernbrötchen",
    "ein knuspriges Laugendreieck",
    "einen Döner mit Mais",
    "eine Portion Nudelsalat",
    "Wok-Gemüse mit Udonnudeln",
    "eine Schüssel Ramen mit einem Alibi-Ei",
    "eine vegane Kringelbratwurst mit Gurkensalat",
    "ein Stück Lasagne nach einem alten Rezept",
    "gut gewürzten Linsensalat",
    "einen Rocula-Wrap mit gehackten Datteln",
    "ein Räuchertofu in Fischform",
    "ein köstliches Drachenfrucht-Dessert",
    "überbackene Champignons mit Aubergine",
    "eine Schüssel cremige Kürbissuppe",
    "einen dampfenden Gemüsemuffin",
    "eine Scheibe frisches Bananenbrot",
    "eine ordentliche Käsestulle",
    "eine Pfanne mit Zucchini-Feta-Gemüse",
    "Spaghetti mit Linsen-Bolonese",
    "ein Stück Lavendel-Honig-Torte",
    "einen Teller knusprige Kroketten",
    "einen Teller Spargel mit Sauce Hollandaise",
    "Zopfbrot",
    "Tteokbokki vom Streetfoodmarkt",
    "eine extra große Pizza mit Paprika",
    "einen Teller Moussaka",
    "ein großes Stück Red-Velvet-Kuchen",
    "eine Portion Pelmeni mit Schmand",
    "eine dampfende Pfanne Paella",
    "ein knuspriges Langos mit Salz und Öl",
    "einen prall gefüllten Frühstücksburrito",
    "ein mehr oder weniger gelungener Linsen-Walnuss-Braten",
    "Gemüsestreifen mit Hummus-Dip",
    "ein Omelett mit Pilzen und Cheddar",
    "eine Pizza Supreme mit gefülltem Rand",
    "zwei französische Tacos mit algerischer Soße",
    "eine deliziöse Schüssel Bouillabaisse",
    "frisch gebackenes Fladenbrot und Oliven",
    "ein extravagantes Spezialgericht mit Goldblättchen und Trüffel",
    "eine winzige Portion Ratatouille mit einem einzelnen Strang Schnittlauch oben drauf",
    "eine kleine Schale Honigpudding",
    "eine Portion dreifach frittierte Pommes mit Mayonnaise",
    "einen Teller Arme-Ritter-Banane",
    "ein perfekt zubereitetes Kartoffelgratin",
    "eine Portion Konjak-Garnelensalat",
    "eine gut pürierte Smoothie-Bowl",
    "einen Corndog",
    "eine Portion welliger Pommes aus dem Schwimmbad-Bistro",
    "eine feine, mit Frischkäse gefüllte, Blätterteigrolle",
    "eine frisch gebackene Kürbispastete",
    "ein Stück Bienenstichkuchen",
    "ein Stück deftigen Gemüsekuchen",
    "dampfende Kartoffelspalten mit Kräuterquark",
    "eine Portion gedünsteten Blumenkohl",
    "ein Blech saftiger Brownies",
    "eine teure Trüffelspezialität",
    "einen Teller Bouletten und grüne Bohnen",
    "eine Portion Bohnen und Zwiebeln",
    "eine Croustade",
    "Reisporridge mit Frühlingszwiebeln",
    "einen gegrillten Gemüsespieß",
    "ein Panna Cotta mit Aprikosenkompott",
    "eine Schale liebevoll geschnittenes Obst",
    "ein halbes Brötchen mit grober Lebervurst",
    "eine große Auswahl an Sushi-Spezialitäten und etwas Sojasoße",
    "eine schmackhafte Ingwerwurzel",
    "eine Portion Süßkartoffelpommes mit Mango-Chutney",
    "eine gut abgeschmeckte Portion Kartoffeleintopf",
    "eine Bockwurst mit Ketchup",
    "eine Portion Schmorgurken",
    "ein Körnerbaguette und Häckerle",
    "eine Scheibe Pumpernickel mit einem hartgekochten Ei",
    "authentisches indisches Curry",
    "fischförmiges Gebäck mit roter Bohnenfüllung",
    "einen köstlichen Auberginenauflauf",
    "eine türkische Pizza",
    "einen Falafeldöner mit extra Soße",
    "einen Teller Pasta Primaverda",
    "eine heiße Ofenkartoffel",
    "eine Pizza mit riesiger Ananasscheibe",
    "eine halbe Pizza mit extra Knoblauch",
    "einen echten Cheeseburger zum Mitnnehmen",
    "einen seltenen niederländischen Bergkäse",
    "ein deftig belegtes Laugenbrötchen",
    "zwei Gemüsefrikadellen mit Tomatensalat",
    "eine Portion Kartoffelstampf mit Zwiebelsoße",
    "eine Portion Konjaklachs in Kräutersud",
    "Kaviar in einer Schale aus purem Gold",
    "Nudeln mit selbstgemachtem Pesto",
    "eine Portion Kartoffeln mit Kohlrabi-Möhren-Gemüse",
    "einen Schokobrunnen und eine Schale Obst",
    "ein deftiges Käse-Fondue",
    "eine mittelgroße Pizza mit Brokkoli und diversem Gemüse",
    "zwei dampfende v-Schnitzel Cordon bleu von Rügenwalder Mühle",
    "hübsch angerichtete Antipasti",
    "ein paar Scheiben Ciabatta mit Bruschetta",
    "einen fruchtigen Salat mit Honigmelone",
    "ein frisches Gemüsebrötchen",
    "Kartoffelpuffer mit Apfelmus",
    "Spinat mit knusprigen Gemüsepommes",
    "eine Schale duftender Fenchelsuppe",
    "eine Schüssel Nudel-Rosenkohl-Eintopf",
    "eine Schale Wrukeneintopf",
    "eine glasierte Streuselschnecke",
    "ein fruchtiger Mandarinenkuchen mit Teigstreuseln",
    "ein Stück Fantakuchen",
    "ein Stück wolkigen Schokoladenkuchen mit Puderzucker",
    "knusprige Süßkartoffelpommes",
    "eine Portion überbackene Aubergine",
    "deftigen Eintopf in einem ausgehöhlten Brotlaib",
    "einen Tortilla-Sombrero mit Guacamole-Rand",
    "ein fürstliches Frühstück",
    "einen Korb frischer Croissants mit einer Auswahl an Marmeladen",
    "zwei gefüllte Donuts",
    "einen gemischten Salat mit Radieschen",
    "zwei getoastete Waffeln",
    "Pflaumenkuchen mit Schlagsahne",
    "einen Teller kalten Nudelsalat",
    "gefüllte Kartoffeltaschen mit würziger Soße",
    "flambierte Crêpe Suzette",
    "ein komplettes Englisches Frühstück mit Black Pudding",
    "ein Nutellatoast mit Bananenscheiben",
    "eine Portion hervorragend abgeschmecktes Rührei",
    "zwei gefüllte rote Paprikas",
    "einen Teller weißen Schichtkohl",
    "in Miso mariniertes und gebackenes Konjak-Fischfilet",
    "ein gegrilltes Tofu mit einer würzigen Tomaten-Curry-Soße",
    "gedämpfte Austernpilze mit knusprigen Pommes",
    "ein Stückchen Nusskuchen",
    "ein Stück Karottenkuchen mit Möhrchendeko",
    "Seitan-Roast mit Yorkshire Pudding",
    "eine Pizza ohne Rand",
    "eine Portion Brokkoli-Kartoffel-Gratin",
    "ein open-faced Sandwich",
    "einen Teller Englische Scones mit Marmelade",
    "eine Portion Kanadische Poutine",
    "eine Schüssel Wirsingkohl",
    "einen ganzen Baumkuchen",
    "einen doppelten Burger mit extra Käse",
    "ein Stück frische Honigwabe",
    "einen Teller Rote-Beete-Suppe mit saurer Sahne",
    "zwölf knusprige v-Wings",
    "ein Stück Lebkuchen-Kuchen",
    "auf offenem Feuer zubereitetes Bulgogi",
    "das legendenumwobene Stück einer italienischen halbgetrockneten Tomate",
    "geschichteten Schokopudding mit Waldbeeren",
    "zwei Stücke Champignon-Spinat-Lasagne",
    "eine Schale Haferbrei mit Honig",
    "eine Portion Reis mit Gemüsefrikassee",
    "Jasminreis mit gedünstetem Kaisergemüse",
    "drei westafrikanische Kichererbsenfrikadellen",
    "eine Auswahl an winterlichen Gebäcken",
    "Sommerrollen mit Teriyaki-Sauce",
    "einen duftenden Bratapfel",
    "selbstgemachte Tacos mit Ortega-Soße",
    "überbackenes Toast Hawaii",
    "einige Stücke russischen Zupfkuchen",
    "gezuckerte Krapfen",
    "eine heiße Apfeltasche",
    "einen Teller mit Herzoginkartoffeln",
    "eine Bratwurst mit mediterranem Salat",
    "Nudeln mit Tomatensoße",
    "Schwammerlsuppe mit Knallpilzen",
    "einen Teller Nudeln mit Fenchelcremesoße",
    "zwei Stücke Pizza Margherita",
    "ein frisches Dresdner Handbrot vom Weihnachtsmarkt",
    "knusprig gebackenen Seitan mit blanchierem Spargel",
    "eine große Portion vegane Gyoza",
    "zwei vegane Kohlrouladen",
    "elegant gerollte Pfannkuchen mit Nutella",
    "elegant gerollte süße Eierkuchen",
    "elegant gerollten, deftigen Palatschinken",
    "elegant gerollte Plinsen mit Apfelmus",
    "ein Koreanisches BBQ mit vierzig Nebengerichten",
    "mundgerechte Schnittlauch-Creme-Röllchen mit Dill",
    "Shoyu-Ramen mit Pak Choi",
    "ofengebackenen Kürbis mit Spinathaube und Mandelsplittern",
    "ein halbes Brötchen mit Eiersalat",
    "ein halbes Brötchen mit v-Mett",
    "ein halbes Brötchen mit v-Fleischsalat",
    "ein halbes Brötchen mit Auberginencreme",
    "ein halbes Brötchen mit selbstgemachtem Kräuterquark",
    "ein Toast mit Avocado und Ei",
    "mexikanische Pommes mit Guacamole und gehackten Tomaten",
    "eine Schale Pigs-in-a-Blanket",
    "einen hervorragend abgeschmeckten klassischen Salat",
    "Schnitzel mit Mischgemüse und Salzkartoffeln",
    "einen Apfel mit einer weißen und einer roten Backe",
    "ein drei-Gänge-Menü von Marco Pierre White",
    "eine übergroße Mandarine",
    "einen Teller Süßkartoffel-Kichererbsen-Curry",
    "zwei dampfende Falafel-Wraps",
    "ein durchgeweichtes Thunvischsandwich",
    "ein paar hartgekochte Eier im Glas mit Schnittlauch obendrauf",
    "eine Schale verführerischen Rucola-Kartoffelsalat",
    "einen Topf Matzah-Ball-Suppe",
    "einen Laib geflochtenes Challah",
    "vegane Pekingente mit Hoisin-Sauce",
    "gefüllte Zucchiniblüten",
    "ein Stück Zwiebelkuchen",
    "eine Schale Buchweizengrütze",
    "ein paar Holunderküchlein",
    "eine Schale Stachyssalat",
    "eine Apfelkaltschale",
    "eine Portion gebackenen Grießpudding",
    "diverse Beignets",
    "einen Teller Äpfel im Schlafrock",
    "zweienhalb Dampfnudeln",
    "eine Schale Gemüsefumet",
    "einen Becher Graupen",
    "Hirse mit brauner Butter",
    "einen Topf Morcheln",
    "eine mehrstöckige Hochzeitstorte",
    "eine Schüssel Pilzragout",
    "kandierte Pomeloschale",
    "einen großen Teller Rosenkohlsuppe",
    "eine Schale Pudding mit echtem Sago",
    "eine Schüssel Blaubeersuppe",
    "vier leicht getoastete Weißtoastscheiben",
    "ein Stück Zitronentarte",
    "steirische Apfeltorte",
    "eine köstliche Rolle Futomaki mit salzreduzierter Sojasauce",
    "ein Brötchen mit veganem Karottenlachs",
#non-good bzw. Referenzen, seltsames, etc.:
    "eine gigantische knusprige Krokette",
    "des Wahnsinns knusprige Beute",
    "eine hastig improvisierte Mahlzeit",
    "eine Tube Zahnpasta mit Pfefferminzgeschmack",
    "eine Portion Spaghetti mit fußballgroßen Hackbällchen",
    "ein modernes Kunstwerk aus Oliven",
    "einen grünlich blubbernden Eintopf im Hexenkessel",
    "einen deftigen Schlammkuchen",
    "eine Dose Tomatensuppe",
    "einen Zauberwürfel aus Gemüsestückchen",
    "ein deckenhoch gestapeltes Sandwich",
    "die falsche Bestellung",
    "die falsche Rechnung",
    "lauwarmen Kichererbsensalat",
    "eine Dose Kidneybohnen und einen Löffel",
    "eine Neuheit aus der modernen Molekularküche",
    "ein Fünf-Sterne-Gericht und eine Lupe",
    "eine Schale Kräuterquark mit 50% Zwiebel",
    "einen Döner ohne Brot",
    "eine Erbsen-Mayonnaise-Pizza",
    "den halben Kühlschrank",
    "eine tiefgefrorene Packung Rosenkohl",
    "eine Schale dünne Suppe mit einem unpraktisch klobigen Holzlöffel",
    "ein Tablett mit undefinierbarem Essen aus der Schulkantine",
    "ein einzelnes rohes Hühnerei",
    "eine Einladung zu einer Kochshow",
    "einen Gutschein zu einem Kochkurs für Anfänger",
    "die Wegbeschreibung zum nächsten Supermarkt",
    "eine Packung Backpulver",
    "ein Schälchen mit Kaffeesatz",
    "nicht weniger als zwanzig Semmelknödel",
    "einen klobig-klebrigen Proteinriegel",
    "eine Portion Spinatgrütze",
    "eine Apfelpastete vom absolut bekloppten Johnson",
    "eine Farce für Suppe",
    "alle veganen Bratwürste und alles Sauerkraut im Topf",
    "das bei Alfred Biolek von Blixa Bargeld gekochte Risotto",
    "eine Portion Obatzter",
    "einen Tortenheber ohne Torte weit und breit",
    "Kartoffelpüree aus der Tüte",
    "eine Schale Elefantencreme",
    "billiges Sushi",
    "eine Portion unterwürzte Macaroni mit Käse",
    "das fliegende Spaghettimonster mit extra großen Tempehbällchen",
    "Albert Einsteins Lieblingsessen: Spaghetti",
    "eine Packung Proteinpulver und Wasser",
    "eine aufgeklappte Calzone",
    "eine Pizza mit ausschließlich Rand",
    "ein Haar in der Suppe",
    "vier Töpfe cremiger Shiitake-Suppe",
    "eine von Javier Milei mit der Motorsäge zurechtgeschnittene Karotte",
    "ein closed-faced Sandwich",
    "zwei Körbe fettiger Pizzabrötchen",
    "eine Liste mit Restaurants in der Nähe",
    "ein Töpfchen mit endlosem süßen Brei",
    "einen Salzstreuer mit fast abgeschraubtem Deckel",
    "ein fest geschlossenes Glas Mayonnaise",
    "das Leibgericht von Theodore Roosevelt",
    "die Bestellung des Sitznachbarn",
    "eine intergalaktische Spezialität",
    "ein Rezept und passende Zutaten",
    "eine schief gewachsene gelbe Paprika",
    "eine Schale ungewürztes Erbsenpüree",
    "einen Krabbenburger mit extra Gürkchen",
    "ein Tablett mit Flugzeugessen",
    "ein Dutzend Kartoffelknödel in Zwiebeltunke",
    "sechs Eimer Kartoffeln",
    "in Zitronenwasser gewaschene Algen mit Wasabi",
    "ein Frühstücks-Abendessen",
    "die abgelaufene Srirachasoße aus dem Kühlschrank",
    "eine Dose Spargel mit kürzlich abgelaufenem Verfallsdatum",
    "Spinat mit gummiartigem Rührei",
    "eine Schale Fertigsalat aus dem Supermarkt",
    "den kulinarischen Epitaph des Küchenchefs",
    "ein halsbrecherisches Stuntmanöver mit klapperndem Geschirr",
    "einen nicht wie die Abbildung auf der Karte aussehenden Burger",
    "die Reste der gestrigen Grillfeier",
    "in Ketchup ertränkte Pommes",
    "die Experimente eines Amateurkochs",
    "eine Dose Mais und einen Löffel",
    "Spaghetti mit einer Fertigsoße",
    "ein paar Gottes Zorn hervorrufende Maultaschen",
    "einen mexikanischen Burrito mit viel zu dicker Tortilla",
    "ein verschmähtes Stück der Krönungsquiche",
    "ein dezent angebrütetes Dinosaurierei",
    "eine Handvoll hartgekochter Wachteleier",
    "eine Plan-9-Tomate aus dem Weltall",
    "eine krachende Kaisersemmel",
    "einen riesigen Königsberger Klops mit Kapernfüllung",
    "einen unverständlichen Gruß aus der Küche",
    "ein unpraktisch hoch belegtes Sandwich",
    "eine Schale kalte Kartoffeln von gestern",
    "das Hologramm eines königlichen Festmahls",
    "eine Tube Astronautennahrung",
    "einen quadratischen Nährstoffwürfel der Zukunft",
    "ein paar aufgeplatzte Wiener Würstchen",
    "Gesundheitssuppe in einer Flasche",
    "eine Schüssel Soup-Soup-Soup",
    "die Überreste vom letzten Abendmahl",
    "einen großen Teller Fingerfood mit ungünstig platzierten Spießchen",
    "ein fest geschlossenes Glas saure Gurken",
    "eine Portion rohe Po-ta-toes (boil'em, mash'em, stick'em in a stew)",
    "einen triefenden Burger",
    "eine Tasse Spargelcremesuppe aus der Tüte",
    "einen ganzen Atlantic-Gigant-Kürbis",
    "eine kandierte Zwiebel",
    "einen Reiskocher und eine Packung Reis",
    "einen deckenhohen Stapel Pfannkuchen und eine Flasche Ahornsirup",
    "eine rohe Knoblauchzehe",
    "eine Portion unauthentische vietnamesische Kost",
    "frittiertes Besteck",
    "einen von Schnecken zerfressenen Kopfsalat",
    "eine Portion von Kronks Spinattaschen",
    "Nudeln, die elf Minuten gekocht wurden",
    "die Reste der Woche",
    "einen Eimer frittiertes Tempeh",
    "eine gefährlich wackelnde Götterspeisetorte",
    "eine erfrischende ganze Gurke",
    "eine Portion Kimchi, extra scharf",
    "einen Teller glitschige Süßkartoffelnudeln",
    "eine Portion Bangers and Mash",
    "eine ganze Ananas",
    "Gourmet-Katzenfutter",
    "ein schmieriges Sandwich mit zu viel Remoulade",
    "eine ominöse grellgrüne Grütze",
    "einen halb gegessenen Pfannkuchen",
    "einen benutzten Teller",
    "ein Glas Erdnussbutter und einen Löffel",
    "eine Portion zappligen Zucchiniauflauf",
    "den Kraftriegel der deutschen Arbeiterklasse",
    "Bratwurst mit Sauerkraut",
    "ein Bündel Petersilie",
    "Stulle mit Brot",
    "abgelaufenes Knäckebrot, das nicht mehr knackt",
    "Rock'n'Roll-Rouladen",
    "eine Schüssel chaotische Chili-sin-Carne",
    "ein unidentifizierbares Experiment mit zu viel zerlaufener Butter",
    "einen Gruß des Küchenlehrlings",
    "eine dreistöckige Tofu-Turbulenz",
    "eine Kelle kalte Gulaschsuppe",
    "einen Handkäs mit Musik",
    "die Reste von gestern",
    "ein Osternest mit Ostereiern",
    "Astronautenfutter",
    "eine Portion Gagh",
    "eine übelriechende Käsesuppe",
    "fünf mexikanische Tacos",
    "einen Berg fettige Ringelpommes",
    "eine meterlange Gurkenspirale",

#Kuchen/Puddings/Süßspeisen die nicht Hauptspeise, Kekse, Eiscreme oder Snacks sind:
    "viel zu viele Waffeln",
    "ein Stück von Tante Mathildas Kirschkuchen"
    "dreizehn üppige Zimtschnecken",
    "aufgetauten Kuchen vom letzten Jahr",
    "ein Lebkuchenhaus mit eingestürztem Dach",
    "einen Kuchen ohne Backpulver",
    "einen Geburtstagskuchen mit zu wenig Kerzen",
    "ein Blech Papageienkuchen",
    "zwei mit Senf gefüllte Donuts",
    "ein schokoladiges Miniaturmodell des Sonnensystems mit Pluto als Kirsche",
    "eine täuschend echte Rolle Toilettenpapier, aber es ist Kuchen",
    "eine Schale tumultuöses Tiramisu",
    "Zuckerwatte mit Einhorngeschmack",
    "ein Stück kichernden Käsekuchen mit Himbeeren",
    "drei Stücke traurige trockene Torte",
    "eine ganze Benjamin-Blümchen-Torte",
    "eine nicht ganz perfekte Crème Brûlée",
    "einen Klumpen Teig, der an einen Kuchen erinnert",
    "ein Stück Hochzeitstorte mit 2 kg Fondant",
    "eine Raffaello-Torte",
    "ein Stück Sägespänekuchen",
    "eine gefährlich wackelnde Götterspeisetorte",
]
