essen = [
    "mit Spinat und Mozzarella gefüllte Kartoffeltaschen",
    "dampfende Baozi, gefüllt mit einer deftigen Mischung aus Chinakohl und Erbsenhack",
    "eine besondere Delikatesse",
    "Bandnudeln mit geröstetem Tofu und Kräutergarnierung",
    "einen Wirsingeintopf",
    "einen Lahmacun",
    "eine Portion Kartoffelbrei",
    "Spinat",
    "einen Seitan Döner",
    "einen Teller Spaghetti Bolognese",
    "einen Teller Spaghetti mit Käsesahnesoße",
    "zwei Käsebrote",
    "Okonomiyaki",
    "feuriges Chili sin Carne",
    "ein fluffiges Rührei",
    "eine leckere Pizza",
    "einen frischen Gurkensalat",
    "einen großen Chefsalat",
    "Schwarzwurzel und Kartoffelbrei",
    "ungarisches Gulasch",
    "Spaghetti mit Soja-Bolognese",
    "ein original französisches Ratatouille",
    "arme Ritter",
    "Pommes mit Majo",
    "leckeren Kartoffelauflauf",
    "einen Toast Hawaii",
    "indisches Gemüse Curry",
    "einen Planted-Gyrosteller mit Tzatziki",
    "Steinpilz-Risotto",
    "ein paar Mini-Frühlingsrollen",
    "würziges Sauerkraut",
    "Bratkartoffeln",
    "asiatisches Wokgemüse",
    "einen Teller mit süßem Milchreis",
    "eine Lasagne",
    "chinesisch gebratene Nudeln",
    "ein Tomaten-Baguette",
    "eine Portion Falafel mit Hummus",
    "ein feuriges Chili con Soja",
    "einen Teller Spaghetti mit Gorgonzolasoße",
    "einen Big Vegan TS",
    "einen McPlant",
    "einen Teller voll Burritos",
    "eine Portion handgerolltes Sushi",
    "ein Butterbrot",
    "eine Schnittlauch-Brezel",
    "einen Teller szegediner Gulasch",
    "eine Portion Avocado Maki",
    "eine Portion Konjaklachs-Maki"
    "eine Spinatlasagne",
    "einen Teller vegetarisch gefüllte Paprika",
    "einen Teller gefüllte Zucchini",
    "ein Schinken-Käse-Omelett",
    "Chop Suey",
    "ein großes Stück Tofurducken",
    "einen Teller Spaghetti Aglio e Olio",
    "Nudeln mit Pesto",
    "einen Teller Paella",
    "einen Berg Pfannkuchen",
    "Grießbrei mit Amarena Kirschen",
    "einen Kaiserschmarrn mit Apfelmus",
    "Palatschinken mit Marillenmarmelade und Staubzucker",
    "eine Schale Grießbrei mit Nutella",
    "ein Gefäß mit Wan Tan",
    "frittierten Tofu auf Eierreis",
    "Kürbiskernbratlinge",
    "veganen Räucherspeck mit frischen Zwiebeln",
    "eine große Portion Tortellini mit Frischkäsefüllung",
    "ein rustikales Krustenbrot mit Bergkäse",
    "dampfenden Kaiserschmarrn",
    "Grießbrei mit roter Grütze",
    "brasilianischen Schwarzbohnen-Eintopf (feijoada)",
    "einen Teller selbstgedrehte Zucchini-Nudeln",
    "mildes Möhrenmischmasch",
    "gegrillten Kürbis",
    "knusprige Frühlingsrollen mit Dip",
    "drei frische Onigiri",
    "entzückendes Erbsengemüse",
    "Wassermelonensalat in einer ausgehöhlten Wassermelone",
    "sauer eingelegten Spargel in Aspik",
    "gedünsteten Brokkoli",
    "gebratenes Gemüse mit Erdnusssoße",
    "Quinoasalat mit feinen Tomaten",
    "einen italienischen Klassiker mit einem ~Spritzer~ Olivenöl",
    "ein selbst gebackenes Kürbiskernbrötchen",
    "einen Döner mit Mais",
    "eine Portion Nudelsalat",
    "Wok-Gemüse mit Udonnudeln",
    "eine Schüssel Ramen mit einem Alibi-Ei",
    "eine vegane Kringelbratwurst mit Gurkensalat",
    "ein Stück Lasagne nach einem alten Rezept",
    "gut gewürzten Linsensalat",
    "einen Rocula-Wrap mit gehackten Datteln",
    "ein Räuchertofu in Fischform",
    "überbackene Champignons mit Aubergine",
    "eine Schüssel cremige Kürbissuppe",
    "einen dampfenden Gemüsemuffin",
    "eine ordentliche Käsestulle",
    "eine Pfanne mit Zucchini-Feta-Gemüse",
    "Spaghetti mit Linsen-Bolonese",
    "einen Teller knusprige Kroketten",
    "einen Teller Spargel mit Sauce Hollandaise",
    "Zopfbrot",
    "Tteokbokki vom Streetfoodmarkt",
    "eine extra große Pizza mit Paprika",
    "einen Teller Moussaka",
    "eine Portion Pelmeni mit Schmand",
    "eine dampfende Pfanne Paella",
    "ein knuspriges Langos mit Salz und Öl",
    "einen prall gefüllten Frühstücksburrito",
    "ein mehr oder weniger gelungener Linsen-Walnuss-Braten",
    "Gemüsestreifen mit Hummus-Dip",
    "ein Omelett mit Pilzen und Cheddar",
    "eine Pizza Supreme mit gefülltem Rand",
    "zwei französische Tacos mit algerischer Soße",
    "eine deliziöse Schüssel Bouillabaisse",
    "frisch gebackenes Fladenbrot und Oliven",
    "ein extravagantes Spezialgericht mit Goldblättchen und Trüffel",
    "eine winzige Portion Ratatouille mit einem einzelnen Strang Schnittlauch oben drauf",
    "eine Portion dreifach frittierte Pommes mit Mayonnaise",
    "einen Teller Arme-Ritter-Banane",
    "ein perfekt zubereitetes Kartoffelgratin",
    "eine Portion Konjak-Garnelensalat",
    "einen Corndog",
    "eine Portion welliger Pommes aus dem Schwimmbad-Bistro",
    "eine feine, mit Frischkäse gefüllte, Blätterteigrolle",
    "eine frisch gebackene Kürbispastete",
    "ein Stück deftigen Gemüsekuchen",
    "dampfende Kartoffelspalten mit Kräuterquark",
    "eine Portion gedünsteten Blumenkohl",
    "eine teure Trüffelspezialität",
    "einen Teller Bouletten und grüne Bohnen",
    "eine Portion Bohnen und Zwiebeln",
    "eine Croustade",
    "Reisporridge mit Frühlingszwiebeln",
    "einen gegrillten Gemüsespieß",
    "ein halbes Brötchen mit grober Lebervurst",
    "eine große Auswahl an Sushi-Spezialitäten und etwas Sojasoße",
    "eine Portion Süßkartoffelpommes mit Mango-Chutney",
    "eine gut abgeschmeckte Portion Kartoffeleintopf",
    "eine vBockwurst mit Ketchup",
    "eine Portion Schmorgurken",
    "ein Körnerbaguette und Häckerle",
    "eine Scheibe Pumpernickel mit einem hartgekochten Ei",
    "authentisches indisches Curry",
    "einen köstlichen Auberginenauflauf",
    "eine türkische Pizza",
    "einen Falafeldöner mit extra Soße",
    "einen Teller Pasta Primaverda",
    "eine heiße Ofenkartoffel",
    "eine Pizza mit riesiger Ananasscheibe",
    "eine halbe Pizza mit extra Knoblauch",
    "einen echten Cheeseburger zum Mitnnehmen",
    "einen seltenen niederländischen Bergkäse",
    "ein deftig belegtes Laugenbrötchen",
    "zwei Gemüsefrikadellen mit Tomatensalat",
    "eine Portion Kartoffelstampf mit Zwiebelsoße",
    "eine Portion Konjaklachs in Kräutersud",
    "Kaviar in einer Schale aus purem Gold",
    "Nudeln mit selbstgemachtem Pesto",
    "eine Portion Kartoffeln mit Kohlrabi-Möhren-Gemüse",
    "ein deftiges Käse-Fondue",
    "eine mittelgroße Pizza mit Brokkoli und diversem Gemüse",
    "zwei dampfende v-Schnitzel Cordon bleu von Rügenwalder Mühle",
    "hübsch angerichtete Antipasti",
    "ein paar Scheiben Ciabatta mit Bruschetta",
    "einen fruchtigen Salat mit Honigmelone",
    "ein frisches Gemüsebrötchen",
    "Kartoffelpuffer mit Apfelmus",
    "Spinat mit knusprigen Gemüsepommes",
    "eine Schale duftender Fenchelsuppe",
    "eine Schüssel Nudel-Rosenkohl-Eintopf",
    "eine Schale Wrukeneintopf",
    "knusprige Süßkartoffelpommes",
    "eine Portion überbackene Aubergine",
    "deftigen Eintopf in einem ausgehöhlten Brotlaib",
    "ein fürstliches Frühstück",
    "einen Korb frischer Croissants mit einer Auswahl an Marmeladen",
    "einen gemischten Salat mit Radieschen",
    "einen Teller kalten Nudelsalat",
    "gefüllte Kartoffeltaschen mit würziger Soße",
    "flambierte Crêpe Suzette",
    "ein komplettes Englisches Frühstück mit Black Pudding",
    "ein Nutellatoast mit Bananenscheiben",
    "eine Portion hervorragend abgeschmecktes Rührei",
    "zwei gefüllte rote Paprikas",
    "einen Teller weißen Schichtkohl",
    "in Miso mariniertes und gebackenes Konjak-Fischfilet",
    "ein gegrilltes Tofu mit einer würzigen Tomaten-Curry-Soße",
    "gedämpfte Austernpilze mit knusprigen Pommes",
    "Seitan-Roast mit Yorkshire Pudding",
    "eine Pizza ohne Rand",
    "eine Portion Brokkoli-Kartoffel-Gratin",
    "ein open-faced Sandwich",
    "einen Teller Englische Scones mit Marmelade",
    "eine Portion Kanadische Poutine",
    "eine Schüssel Wirsingkohl",
    "einen doppelten Burger mit extra Käse",
    "einen Teller Rote-Beete-Suppe mit saurer Sahne",
    "zwölf knusprige v-Wings",
    "auf offenem Feuer zubereitetes Bulgogi",
    "das legendenumwobene Stück einer italienischen halbgetrockneten Tomate",
    "zwei Stücke Champignon-Spinat-Lasagne",
    "eine Schale Haferbrei mit Honig",
    "eine Portion Reis mit Gemüsefrikassee",
    "Jasminreis mit gedünstetem Kaisergemüse",
    "drei westafrikanische Kichererbsenfrikadellen",
    "Sommerrollen mit Teriyaki-Sauce",
    "selbstgemachte Tacos mit Ortega-Soße",
    "überbackenes Toast Hawaii",
    "einen Teller mit Herzoginkartoffeln",
    "eine vBratwurst mit mediterranem Salat",
    "Nudeln mit Tomatensoße",
    "einen Teller Nudeln mit Fenchelcremesoße",
    "zwei Stücke Pizza Margherita",
    "ein frisches Dresdner Handbrot vom Weihnachtsmarkt",
    "knusprig gebackenen Seitan mit blanchierem Spargel",
    "eine große Portion vegane Gyoza",
    "zwei vegane Kohlrouladen",
    "elegant gerollte Pfannkuchen mit Nutella",
    "elegant gerollte süße Eierkuchen",
    "elegant gerollten, deftigen Palatschinken",
    "elegant gerollte Plinsen mit Apfelmus",
    "ein Koreanisches BBQ mit vierzig Nebengerichten",
    "mundgerechte Schnittlauch-Creme-Röllchen mit Dill",
    "Shoyu-Ramen mit Pak Choi",
    "ofengebackenen Kürbis mit Spinathaube und Mandelsplittern",
    "ein halbes Brötchen mit Eiersalat",
    "ein halbes Brötchen mit v-Mett",
    "ein halbes Brötchen mit v-Fleischsalat",
    "ein halbes Brötchen mit Auberginencreme",
    "ein halbes Brötchen mit selbstgemachtem Kräuterquark",
    "ein Toast mit Avocado und Ei",
    "mexikanische Pommes mit Guacamole und gehackten Tomaten",
    "eine Schale Plants-in-a-Blanket",
    "einen hervorragend abgeschmeckten klassischen Salat",
    "Schnitzel mit Mischgemüse und Salzkartoffeln",
    "einen Apfel mit einer weißen und einer roten Backe",
    "ein drei-Gänge-Menü von Marco Pierre White",
    "eine übergroße Mandarine",
    "einen Teller Süßkartoffel-Kichererbsen-Curry",
    "zwei dampfende Falafel-Wraps",
    "ein durchgeweichtes Thunvischsandwich",
    "ein paar hartgekochte Eier im Glas mit Schnittlauch obendrauf",
    "eine Schale verführerischen Rucola-Kartoffelsalat",
    "einen Topf Matzah-Ball-Suppe",
    "einen Laib geflochtenes Challah",
    "vegane Pekingente mit Hoisin-Sauce",
    "gefüllte Zucchiniblüten",
    "ein Stück Zwiebelkuchen",
    "eine Schale Buchweizengrütze",
    "eine Schale Stachyssalat",
    "eine Portion gebackenen Grießpudding",
    "zweienhalb Dampfnudeln",
    "eine Schale Gemüsefumet",
    "einen Becher Graupen",
    "Hirse mit brauner Butter",
    "einen Topf Morcheln",
    "eine Schüssel Pilzragout",
    "einen großen Teller Rosenkohlsuppe",
    "eine Schüssel Blaubeersuppe",
    "vier leicht getoastete Weißtoastscheiben",
    "Kirschsuppe mit Klüten"
    "eine köstliche Rolle Futomaki mit salzreduzierter Sojasauce",
    "ein Brötchen mit veganem Karottenlachs",
    "Pancakes mit Ahornsirup",
    "ein frisches Laugenbrötchen",
    "ein noch warmes Kartoffelbrötchen",
    "eine Bento-Box mit aufwendig in Oktopusform geschnitzten Würstchen",
    "einen großen Flatschen Shepherd's Pie",
    "eine große Schale Bibimbap mit Chilipaste",
    "zwei Pfannkuchen mit Frühlingszwiebeln",
    "einen deftigen Kebab mit drei verschiedenen Soßen",
    "Tofu-Nuggies",
    "einen tollen Gemüseeintopf, mhh",
    "die Reste eines royalen Banketts",
    "ein halbes Brötchen mit Meerrettich und Radieschenscheiben",
    "mit Plätzchenausstechern geformte Sandwichstücke ohne Rand",
    "einen deftigen Black-Bean-Burger",
    "gebackenen Karfiol mit Kartoffelsalat und einer atmosphärischen Kerze",
    "eine deftige Tomaten-Ziegenkäse-Tarte",
    "eine Quiche Lorraine mit vSpeck, Zwiebeln und Käse",
    "zwei Stücke deftige Spargelquiche",
    "Pannenkoeken mit Pilzen und Zucchini",
    "Tomate, Mozzarella und Tapenade",
    "Pizza mit Brokkoli, Zucchini und Aubergine",
    "eine Bento-Box mit liebevoll geschnitzten Hasen-Möhrchen",
    "ein Stück Gemüselasagne auf einem Teller mit Goldrand",
    "eine Portion kalte Buchweizennudeln",
    "cremiges Risotto mit geröstetem Butternut-Kürbis und Salbei",
    "knusprige Falafel mit hausgemachtem Tzatziki und Pita",
    "geröstete Rote-Bete-Scheiben mit Ziegenkäse, Walnüssen und Rucola",
    "angebratenen Tofu mit würziger Walnusssoße",
    "ein Clubsandwich mit veganer Agaven-Chimichurri-Mayo",
    "gegrilltes Gemüse mit Parmesan-Rosmarin-Mayo",
    "einen Caesar-Wrap mit holländischer Erdnuss-Mayo",
    "einen BBQ-Wrap mit Coleslaw",
    "zwei glänzend-knusprige Blätterteigtaschen mit Champignon-Kräuter-Füllung",
    "einen mediterranen Wrap mit gegrillter Aubergine, Feta, Oliven und Oregano",
    "einen saftigen Trüffel-Pilz-Burger mit Rucola und Mayo",
    "einen mexikanischen Burrito mit schwarzen Bohnen, Mais und Salsa",
    "eine Schüssel Gesundheitssüppchen mit einer Scheibe Butterbrot",
    "eine Champignonsuppe in einem kleinen Gefäß mit zwei Henkeln",
    "einen knackigen Salat mit Zitronen-Aioli",
    "eine Schüssel Mangoldsalat mit Gurke und Paprika",
    "Wildkräutersalat mit Ziegenkäse",
    "eine Portion Minari (Wassersellerie), blanchiert und gewürzt",
    "einen knusprigen Gemüsepancake",
    "einen saftigen Burger mit Erbsen-Patty",
    "Onigiri mit eingelegten Pflaumen",
    "einen knackigen Brennnesselsalat",
    "Rahmspinat, roh geriebene Karotten und Weizenkeime",
    "Knäckebrot mit Ziegenfrischkäse und daraufgestreuten Kichererbsen",
    "eine Schale Borschtsch mit einem Klecks Smetana",
    "Okragemüse mit Lupinen-Tempeh und Kurkuma-Quinoa",
    "Toast mit Aprikosenmarmelade",
    "zwei Scheiben Toast mit Stachelbeermarmelade",
    "Toast mit ungesüßter Orangenmarmelade",
    "eine dreistöckige Etagere mit Fingersandwiches",
    "Wraps aus Würztofu, Gurken und Zwiebeln",
    "eine Schüssel veganen Kartoffelsalat",
    "ein entspanntes Frühstück in einer gemütlichen Ecke des Gewächshauses",
    "Pizza mit frischem Giersch aus dem Garten",
    "knusprigen, über dem Lagerfeuer gebackenen Knüppelkuchen",
    "einen dampfenden Topf Linsensuppe",
    "selbstgemachte Hagebuttenmarmelade",
    "eine vegane Pizza",
    "knackigen Löwenzahnsalat",
    "Brokkolicremesuppe",
    "Grünkern-Bratlinge mit Joghurt-Dip",
    "ein liebevoll zubereitetes Pausenbrot",
    "über dem Feuer geschmorte Tüften",
    "eine bunte Auswahl an saisonalem Gemüse",
    "Bohneneintopf",
    "original koreanisches Kimchi",
    "Hacksteak ohne Hack",
    "Spaghetti mit Bärlauchpesto",
    "glutenfreies Körnerbrot",
    "frischen regionalen Spargel mit Frühkartoffeln",
    "eine frische Gemüsepastete",
    "Porridge mit einer Auswahl an Beeren",
    "Königsgemüse in Rahm",
    "Chili-Cheese-Nuggets aus dem Airfryer",
    "einen riesigen gebratenen Pilz mit Frischkäsefüllung",
    "Auberginenlasagne",
    "ein Papptellerchen mit veganer Currywurst",
    "eine Schale durchgezogenes Chili und einen Kanten Brot",
    "Ofengemüse mit Hummus",
    "Quinoasalat mit Erbsen und Frühlingszwiebeln",
    "einen Bambusdämpfkorb mit fünf duftenden Baozi",
    "eine deftige taiwanesische Nudelsuppe mit dezenter Zimtnote",
    "eine deftige Portion Mac and Cheese",
    "zwei dampfende Reis-Bohnen-Burritos",
    "Proteinbällchen, dazu Salat, Pita und Tzatziki",
    "vegetarisches Filet Wellington mit saftig-erdiger Pilznote",
    "böhmische Knödel mit Rotkraut und dunkler Soße",
    "eine Portion eingelegten Weißkrautsalat und eine Gabel",
    "eine richtig heiße Glutkartoffel",
    "einen Teller himmlischer Schupfnudeln",
    "mit Sesam ummanteltes Inside-out-Sushi",
    "Smörgås, echte schwedische Sandwiches, dazu frische Milch und hinterher Eis",
    "einen Halloumi-Burger mit Avocado",
    "würzige Champignon-Spaghetti",
    "rote Linsen-Kokos-Suppe",
    "eine bunte Bulgur-Bowl",
    "Pulled-Pilz mit Süßkartoffelpommes",
    "Tortellini in Tomatensoße",
    "Flammkuchen mit Frühlingszwiebeln",
    "Flammkuchen-Baguettes",
    "Selleriesuppe mit Apfel",
    "gebackenen Camembert mit Preiselbeersoße",
    "deftigen gebratenen Reis",
    "gebratene Maultaschen mit Gemüse",
    "Gnocchi aus der Heißluftfritteuse",
    "eine Gnocchi-Pfanne mit Gorgonzola",
    "eine Portion griechischen Tomatenreis mit Salat",
    "Tofu süß-sauer",
    "eine Portion Kohlrabi-Pommes",
    "Low-Carb-Blumenkohlpüree",
    "eine Schale Tofuwürstchen-Gulasch",
    "panierte Champignons aus dem Airfryer",
    "duftende Rosmarinkartoffeln",
    "Tomatenquiche",
    "Spieße mit Halloumi und gegrilltem Gemüse",
    "deftige vegane Albóndigas",
    "gebratene Mie-Nudeln",
    "Glasnudelsalat und Stäbchen",
    "eine riesige Backkartoffel mit Gemüsefüllung und Datteldip",
    "delikaten Fenchelsalat mit Penne",
    "einen frischen Salat aus Chicorée, Petersilie und Orange",
    "Quetschkartoffeln mit Salat",
    "ein Eiweißbrot-Sandwich mit Avocado und Sprossen",
    "gefüllte Tomaten",
    "Wirsingrouladen mit Tempeh-Füllung und Sesamsoße",
    "Flammkuchen mit Konjak-Lachs und Rucola",
    "Erbsen-Kokos-Reisküchlein",
    "Mandel-Nuss-Tofu",
    "einen saftigen Austernpilz-Burger",
    "zwei Crunch-Wraps",
    "ein großes paniertes Sellerie-Schnitzel",
    "Mangold und Quinoa mit Ziegenkäsesoße",
    "fünf vegane Seitan-Grillfackeln",
    "Tofu-Steaks mit Nusskruste vom Grill",
    "Chili-Mais-Eintopf",
    "gegrillten Spitzkohlsalat mit Nüssen",
    "gegrillte Quesadillas",
    "Fettuccine in Trüffelsoße",
    "Fenchel-Pinienkern-Risotto",
    "Pellkartoffeln mit dreierlei Quark und roter Bete",
    "einige Laugenburger mit Brokkolipatties",
    "Pizzabrötchen mit Spinat",
    "Spargel-Erdbeer-Couscous",
    "einen Stapel Tomaten-Auberginen-Paninis",
    "frischen Apfel-Rettich-Salat",
    "ein herrliches Gemüse-Crumble",
    "ein Baguette Deluxe",
    "eine goldene Schüssel mit köstlicher Minestrone",
    "zunächst eine Kressecremesuppe, danach ein Kompott aus frischem Rhabarber",
    "eine kräftige Bauernpfanne: verschiedene Karottensorten, Bohnen, Zwiebeln",
    "Tortellini mit Ricotta, Spinat und Walnüssen",
    "veganes Katsu-Curry",
    "Tofu, Reis und Edamame",
    "eine herzhafte Joghurt-Bowl",
    "Empanadas mit Bohnenfüllung",
    "Flammkuchen mit Rotkohl und Ziegenkäse",
    "Flammkuchen mit Birne, Gorgonzola und Walnuss",
    "knusprige Kürbisbällchen mit Paprikasoße",
    "Laugenpizza mit Frühlingszwiebeln",
    "würzig glasierte Möhren",
    "v-Gyros mit Feigenbeilage",
    "eine gesunde Umami-Bowl mit Edamame",
    "vegane Satay-Spieße mit Erdnusssoße",
    "Ravioli mit Salbeibutter",
    "Enoki- und Shiitake-Pilze aus dem Ofen",
    "Belugalinsen-Salat",
    "Spinatknödel mit Parmesan",
    "einen Salat aus Staudensellerie und Belugalinsen",
#non-good bzw. Referenzen, seltsames, etc.:
    "Durianfruchtfleisch, das geschmacklich leicht an Zwiebeln, aber auch an Banane erinnert",
    "eine karierte Decke und einen Picknickkorb, der aus allen Nähten platzt vor lauter Köstlichkeiten",
    "eine gigantische knusprige Krokette",
    "des Wahnsinns knusprige Beute",
    "eine hastig improvisierte Mahlzeit",
    "eine Tube Zahnpasta mit Pfefferminzgeschmack",
    "eine Portion Spaghetti mit fußballgroßen Hackbällchen",
    "ein modernes Kunstwerk aus Oliven",
    "einen grünlich blubbernden Eintopf im Hexenkessel",
    "einen deftigen Schlammkuchen",
    "eine Dose Tomatensuppe",
    "einen Zauberwürfel aus Gemüsestückchen",
    "ein deckenhoch gestapeltes Sandwich",
    "die falsche Bestellung",
    "die falsche Rechnung",
    "lauwarmen Kichererbsensalat",
    "eine Dose Kidneybohnen und einen Löffel",
    "eine Neuheit aus der modernen Molekularküche",
    "ein Fünf-Sterne-Gericht und eine Lupe",
    "eine Schale Kräuterquark mit 50% Zwiebel",
    "einen Döner ohne Brot",
    "eine Erbsen-Mayonnaise-Pizza",
    "den halben Kühlschrank",
    "eine tiefgefrorene Packung Rosenkohl",
    "eine Schale dünne Suppe mit einem unpraktisch klobigen Holzlöffel",
    "ein Tablett mit undefinierbarem Essen aus der Schulkantine",
    "ein einzelnes rohes Hühnerei",
    "eine Einladung zu einer Kochshow",
    "einen Gutschein zu einem Kochkurs für Anfänger",
    "die Wegbeschreibung zum nächsten Supermarkt",
    "eine Packung Backpulver",
    "ein Schälchen mit Kaffeesatz",
    "nicht weniger als zwanzig Semmelknödel",
    "einen klobig-klebrigen Proteinriegel",
    "eine Portion Spinatgrütze",
    "eine Apfelpastete vom absolut bekloppten Johnson",
    "eine Farce für Suppe",
    "alle veganen Bratwürste und alles Sauerkraut im Topf",
    "das bei Alfred Biolek von Blixa Bargeld gekochte Risotto",
    "eine Portion Obatzter",
    "einen Tortenheber ohne Torte weit und breit",
    "Kartoffelpüree aus der Tüte",
    "eine Schale Elefantencreme",
    "billiges Sushi",
    "eine Portion unterwürzte Macaroni mit Käse",
    "das fliegende Spaghettimonster mit extra großen Tempehbällchen",
    "Albert Einsteins Lieblingsessen: Spaghetti",
    "eine Packung Proteinpulver und Wasser",
    "eine aufgeklappte Calzone",
    "eine Pizza mit ausschließlich Rand",
    "ein Haar in der Suppe",
    "vier Töpfe cremiger Shiitake-Suppe",
    "eine von Javier Milei mit der Motorsäge zurechtgeschnittene Karotte",
    "ein closed-faced Sandwich",
    "zwei Körbe fettiger Pizzabrötchen",
    "eine Liste mit Restaurants in der Nähe",
    "ein Töpfchen mit endlosem süßen Brei",
    "einen Salzstreuer mit fast abgeschraubtem Deckel",
    "ein fest geschlossenes Glas Mayonnaise",
    "das Leibgericht von Theodore Roosevelt",
    "die Bestellung des Sitznachbarn",
    "eine intergalaktische Spezialität",
    "ein Rezept und passende Zutaten",
    "eine schief gewachsene gelbe Paprika",
    "eine Schale ungewürztes Erbsenpüree",
    "einen Krabbenburger mit extra Gürkchen",
    "ein Tablett mit Flugzeugessen",
    "ein Dutzend Kartoffelknödel in Zwiebeltunke",
    "sechs Eimer Kartoffeln",
    "in Zitronenwasser gewaschene Algen mit Wasabi",
    "ein Frühstücks-Abendessen",
    "die abgelaufene Srirachasoße aus dem Kühlschrank",
    "eine Dose Spargel mit kürzlich abgelaufenem Verfallsdatum",
    "Spinat mit gummiartigem Rührei",
    "eine Schale Fertigsalat aus dem Supermarkt",
    "den kulinarischen Epitaph des Küchenchefs",
    "ein halsbrecherisches Stuntmanöver mit klapperndem Geschirr",
    "einen nicht wie die Abbildung auf der Karte aussehenden Burger",
    "die Reste der gestrigen Grillfeier",
    "in Ketchup ertränkte Pommes",
    "die Experimente eines Amateurkochs",
    "eine Dose Mais und einen Löffel",
    "Spaghetti mit einer Fertigsoße",
    "ein paar Gottes Zorn hervorrufende Maultaschen",
    "einen mexikanischen Burrito mit viel zu dicker Tortilla",
    "ein verschmähtes Stück der Krönungsquiche",
    "ein dezent angebrütetes Dinosaurierei",
    "eine Handvoll hartgekochter Wachteleier",
    "eine Plan-9-Tomate aus dem Weltall",
    "eine krachende Kaisersemmel",
    "einen riesigen Königsberger Klops mit Kapernfüllung",
    "einen unverständlichen Gruß aus der Küche",
    "ein unpraktisch hoch belegtes Sandwich",
    "eine Schale kalte Kartoffeln von gestern",
    "das Hologramm eines königlichen Festmahls",
    "eine Tube Astronautennahrung",
    "einen quadratischen Nährstoffwürfel der Zukunft",
    "ein paar aufgeplatzte Wiener Würstchen",
    "Gesundheitssuppe in einer Flasche",
    "eine Schüssel Soup-Soup-Soup",
    "die Überreste vom letzten Abendmahl",
    "einen großen Teller Fingerfood mit ungünstig platzierten Spießchen",
    "ein fest geschlossenes Glas saure Gurken",
    "eine Portion rohe Po-ta-toes (boil'em, mash'em, stick'em in a stew)",
    "einen triefenden Burger",
    "eine Tasse Spargelcremesuppe aus der Tüte",
    "einen ganzen Atlantic-Gigant-Kürbis",
    "eine kandierte Zwiebel",
    "einen Reiskocher und eine Packung Reis",
    "einen deckenhohen Stapel Pfannkuchen und eine Flasche Ahornsirup",
    "eine rohe Knoblauchzehe",
    "eine Portion unauthentische vietnamesische Kost",
    "frittiertes Besteck",
    "einen von Schnecken zerfressenen Kopfsalat",
    "eine Portion von Kronks Spinattaschen",
    "Nudeln, die elf Minuten gekocht wurden",
    "die Reste der Woche",
    "einen Eimer frittiertes Tempeh",
    "eine gefährlich wackelnde Götterspeisetorte",
    "eine erfrischende ganze Gurke",
    "eine Portion Kimchi, extra scharf",
    "einen Teller glitschige Süßkartoffelnudeln",
    "eine Portion Bangers and Mash",
    "eine ganze Ananas",
    "Gourmet-Katzenfutter",
    "ein schmieriges Sandwich mit zu viel Remoulade",
    "eine ominöse grellgrüne Grütze",
    "einen halb gegessenen Pfannkuchen",
    "einen benutzten Teller",
    "ein Glas Erdnussbutter und einen Löffel",
    "eine Portion zappligen Zucchiniauflauf",
    "den Kraftriegel der deutschen Arbeiterklasse",
    "ein Bündel Petersilie",
    "Stulle mit Brot",
    "abgelaufenes Knäckebrot, das nicht mehr knackt",
    "Rock'n'Roll-Rouladen",
    "eine Schüssel chaotische Chili-sin-Carne",
    "ein unidentifizierbares Experiment mit zu viel zerlaufener Butter",
    "einen Gruß des Küchenlehrlings",
    "eine dreistöckige Tofu-Turbulenz",
    "eine Kelle kalte Gulaschsuppe",
    "einen Handkäs mit Musik",
    "die Reste von gestern",
    "ein Osternest mit Ostereiern",
    "Astronautenfutter",
    "eine Portion Gagh",
    "eine übelriechende Käsesuppe",
    "fünf mexikanische Tacos",
    "einen Berg fettige Ringelpommes",
    "eine meterlange Gurkenspirale",
    "Schwammerlsuppe mit Knallpilzen",
    "einen Tortilla-Sombrero mit Guacamole-Rand",
    "einen riesigen, gefüllten Pizza-Donut",
    "ein bisschen Ingwer, Kreuzkümmel, Asafoetida und Garam Masala",
    "eine hochwertige 5-Minuten-Terrine",
    "ein ganzes Blech Nudelgratin",
    "Kartoffeleintopf mit Knackern",
    "ungewürztes, aber sehr kalorienreiches Babygläschen mit einem Minilöffel",
    "ein weich gekochtes Frühstücksei mit winzigem Silberlöffel",
    "ein in Zitronensaft getränktes Minischnitzel",
    "eine deliziöse Hasenstulle aus der Brotdose von gestern",
    "ein Mischbrot mit gesalzener Butter",
    "eine Schale intergalaktischer Zerealien mit blauer Milch",
    "knackiger intergalaktischer Salat",
    "ein paar violette Pommes mit Trüffelmayo",
    "dein imaginäres Lieblingsgericht",
    "einen Busch Basilikum",
    "ein ausgehöhltes Brötchen mit den Chili-Resten von gestern",
    "eine Milchschnitte in der Größe eines PKWs",
    "zwei frittierte Sushi-Tacos",
    "Rotkohl mit Sauerkraut",
    "einen Spritzkuchen aus dem Spritzenhaus",
    "Tante Mathildas verbrannten Schmorbraten",
    "ein einzelnes Senfei",
    "Bahnhof und Bratkartoffeln",
    "Mohrrüben, und das womöglich zum Mittag",
    "zu jeder Mahlzeit eine Scheibe Butterbrot",
    "das neueste Ernährungsprogramm von Justus Jonas",
    "einen Rettich, in den du deine Zähne schlagen kannst",
    "eine hölzerne Farbpalette mit winzigen bunten Burgern",
    "ein Laib Roggenvollkornbrot ohne Rand",
    "Erdbeerscheiben auf Toast",
    "in Sülze eingelegtes Gemüse mit Kartoffelpüree",
    "einen Flatschen Süßkartoffelpüree",
    "pikantes Petersilienpüree",
    "einen deftigen Räuberteller",
    "eine Portion leckere Hokuspokus-Puffer",
    "einmal Seppels Spezial-Bolo",
    "eine Schwammerlsuppe aus dem Räuberwald und dazu ein Seil",
    "einmal Zwackelmanns Zauberklöße",
    "eine Portion Großmutters Bratwürste mit Sauerkraut und Stampfkartoffeln",
    "einen Räuberschmaus",
    "einen Teller voll Brennnesselsuppe für Mutige",
    "einen unkenförmigen Pfannkuchen",
    "eine Portion feines Gemüse mit Feenkraut",
    "eine Portion armer Räuber",
    "eine Schale voll Kasperlschmarrn mit roter Zipfelmützengrütze",
    "ein leckeres Stockbrot – gut gewickelt ist halb gewonnen",
    "einen Lagerfeuer-Nachtisch",
    "einen Knallpilz-Muffin",
    "einen senfgefüllten Berliner",
    "eine dampfende Dampfnudel",
    "einen Paradiesapfel",
    "eine Badewanne voll Hummus",
    "einen Germknödel mit einem Berg Buttermohn",
    "einen Räuber-Käsefuß aus Blätterteig … und, na ja, Käse",
    "eine vollwertige Mahlzeit aus einer Vollwertkneipe in Rocky Beach",
    "Pita … also Brot … mit Alfalfa und Mungbohnen",
    "Alfa... nee, Alfalfa ... (nein, nicht die Hauptstadt von Afrika, sondern Sprossen der Luzerne. Sie schmecken und sind gesund)",
    "einen Monatsvorrat Lembas-Brot",
    "Kräuter, bei Neumond gesammelt",
    "Hummus mit extra viel Knoblauch und einem Löffel",
    "ein von Mrs Hudson zubereitetes original englisches Frühstück",
    "Bottys Lieblingsessen",
    "einen Korb voll Äpfel",
    "einen Granatapfel und eine Schürze",
    "die Haferkiste von Indian Queen",
    "Mittagessen – denn Schatzsucher brauchen eine Stärkung!",
    "einen leeren Kochtopf",
    "einen leeren Teller",
    "ein vergilbtes Kochbuch mit Großmutters Geheimrezepten",
    "Club-Sandwiches auf viel zu großen Tellern, in viel zu kleinen Portionen",
    "einen Schlüssel und ein belegtes Brot in einem Klarsichtbeutel",
    "einen Kirschbaum und eine Leiter",
    "falschen falschen Hasen aus Erbsenprotein",
    "eine Pyramide aus frittierten Kräuter-Frischkäse-Bällchen",
    "eine große Schüssel Rosenkohlsalat",
    "eine deftige Pilzstulle",
    "ein saftiges Pickle-Sandwich",
    "fruchtige Apfel-Himbeer-Kirsch-Zitronen… ehm, Creme",
    "einen Flatschen unterwürztes Porree-Porridge",
#Kuchen/Puddings/Süßspeisen die nicht Hauptspeise, Kekse, Eiscreme oder Snacks sind:
    "viel zu viele Waffeln",
    "ein Stück von Tante Mathildas Kirschkuchen"
    "dreizehn üppige Zimtschnecken",
    "aufgetauten Kuchen vom letzten Jahr",
    "ein Lebkuchenhaus mit eingestürztem Dach",
    "einen Kuchen ohne Backpulver",
    "einen Geburtstagskuchen mit zu wenig Kerzen",
    "ein Blech Papageienkuchen",
    "zwei mit Senf gefüllte Donuts",
    "ein schokoladiges Miniaturmodell des Sonnensystems mit Pluto als Kirsche",
    "eine täuschend echte Rolle Toilettenpapier, aber es ist Kuchen",
    "eine Schale tumultuöses Tiramisu",
    "Zuckerwatte mit Einhorngeschmack",
    "ein Stück kichernden Käsekuchen mit Himbeeren",
    "drei Stücke traurige trockene Torte",
    "eine ganze Benjamin-Blümchen-Torte",
    "eine nicht ganz perfekte Crème Brûlée",
    "einen Klumpen Teig, der an einen Kuchen erinnert",
    "ein Stück Hochzeitstorte mit 2 kg Fondant",
    "eine Raffaello-Torte",
    "ein Stück Sägespänekuchen",
    "eine gefährlich wackelnde Götterspeisetorte",
    "einen Obstteller",
    "zwei Stück Erdbeertorte",
    "einen Teller Belgische Waffeln mit Schokosoße",
    "eine Portion Reispudding",
    "eine Schale Stachelbeerkompott",
    "Eierlikörkuchen mit vollständig ausgebackenem Eierlikör",
    "einen runderneuerten Obstkuchen mit upgegradeten Erdbeeren",
    "ein köstliches Drachenfrucht-Dessert",
    "eine Scheibe frisches Bananenbrot",
    "ein Stück Lavendel-Honig-Torte",
    "ein großes Stück Red-Velvet-Kuchen",
    "eine gut pürierte Smoothie-Bowl",
    "ein Stück Bienenstichkuchen",
    "ein Blech saftiger Brownies",
    "ein Panna Cotta mit Aprikosenkompott",
    "einen Schokobrunnen und eine Schale Obst",
    "eine glasierte Streuselschnecke",
    "ein fruchtiger Mandarinenkuchen mit Teigstreuseln",
    "ein Stück Fantakuchen",
    "ein Stück wolkigen Schokoladenkuchen mit Puderzucker",
    "zwei gefüllte Donuts",
    "zwei getoastete Waffeln",
    "Pflaumenkuchen mit Schlagsahne",
    "ein Stückchen Nusskuchen",
    "ein Stück Karottenkuchen mit Möhrchendeko",
    "einen ganzen Baumkuchen",
    "ein Stück Lebkuchen-Kuchen",
    "geschichteten Schokopudding mit Waldbeeren",
    "eine Auswahl an winterlichen Gebäcken",
    "einen duftenden Bratapfel",
    "einige Stücke russischen Zupfkuchen",
    "gezuckerte Krapfen",
    "eine heiße Apfeltasche",
    "ein paar Holunderküchlein",
    "eine Apfelkaltschale",
    "diverse Beignets",
    "einen Teller Äpfel im Schlafrock",
    "eine mehrstöckige Hochzeitstorte",
    "ein Stück Zitronentarte",
    "steirische Apfeltorte",
    "einen Rührkuchen",
    "einen veganen glutenfreien Karottenkuchen",
    "einen saftigen Schokokuchen",
    "eine Kirschtorte",
    "einen Apfelkuchen",
    "einen Pudding-Streuselkuchen",
    "einen Rhabarberstreuselkuchen",
    "einige perfekt zubereitete Churros mit Karamellsoße",
    "einen Blaubeer-Joghurt-Gugelhupf",
    "zwei Waffeln mit knusprigem Haselnusscrunch, frischen Beeren und Karamellsoße",
    "ein Stück Plumpudding",
    "ein Stück Plumpudding mit einer Münze darin",
    "ein Stück Rhabarberkuchen mit Baiser",
    "Beignets mit Puderzucker",
    "einen ganzen Kürbis-Pie, gewürzt mit Zimt und Nelken",
    "ein Stück Pecan Pie mit Karamellfüllung",
    "eine Bananen-Creme-Tarte",
    "ein Stück Birnen-Mandel-Tarte",
    "eine halbe Süßkartoffel-Quiche mit Muskatnuss",
    "ein Stück fluffigen Cheesecake mit Pistazien obendrauf",
    "Pannenkoeken mit Apfelscheiben und Rosinen",
    "Pannenkoeken mit Erdbeeren und Schlagsahne",
    "Pannenkoeken mit gegrilltem Marshmallow und Keks",
    "grob gezuckerte Bananen-Waffeln",
    "eine Kaffeetafel mit duftenden Madeleines",
    "den besten Käsekuchen, der jemals deine Geschmacksknospen berührte",
    "eine herrliche Obsttorte",
    "einen wobbelnden Pudding mit Chai-Geschmack und Sahnehäubchen",
    "über Nacht gequollenen Couscous-Pudding mit frischen Früchten",
    "ein extra großes Stück Geburtstagskuchen",
    "ein Stück veganen Käsekuchen",
    "eine Kelle selbst gekochtes Apfelmus",
    "original britisches Pfirsich-Crumble",
    "eine berüchtigte Käse-Sahne-Torte",
    "einen geschmolzenen Marillenknödel",
    "Schokoladensushi mit Puffreis und frischen Früchten",
    "gezuckerte Erdbeeren in Milch",
    "ein Stück von Großmutters berühmtem Pflaumenkuchen",
    "einmal Frau Schlotterbecks magischen Streuselkuchen",
    "eine Hotzenplotz-Torte",
    "einen Zimtwickel am Räuberspieß",
    "eine Teigschüssel zum Ausschlecken",
    "liebevoll zubereitete Pflaumenknödel",
    "eine fluffige Torte mit wunderschönem Pfirsich-Maracuja-Fruchtspiegel",
    "einen noch in der Kastenform ruhenden Honigkuchen",
    "Ricottakuchen vom Feinsten",
    "Mohnkuchen vom Blech",
    "No-Bake-Himbeerkuchen",
    "Quarkkuchen mit Rosinen",
    "einen Brettspielkuchen mit genug Gummibärchen-Figuren für vier Spieler",
    "eine aufwändig verzierte Pinata-Torte, die mit Smarties gefüllt ist",
    "Kirsch-Schmand-Schnitten",
    "Süßkartoffelwaffeln",
    "Erdbeer-Tiramisu mit Haselnusswaffeln",
    "Grießauflauf mit heißen Brombeeren",
    ]
