giveextras = [
    "eine Rolle Toilettenpapier",
    "eine Schmerztablette",
    "eine Packung Girlanden",
    "...äh serviert ist das falsche Wort, gibt sollte das heißen, eine Decke.",
    "eine Wärmflasche in Teddy Bezug",
    "einen Gartenteich voll Kraft",
    "ein Fass Kraft",
    "eine Tonne Kraft",
    "einen knuddelverrückten Kraft-Glücksbringer",
    "einen Kubikmeter Kraft",
    "viel Kraft... sehr viel",
    "eine Packung bunte Taschentücher",
    "einen Eimer gute Laune",
    "einen Orden",
    "die Rechnung",
    "eine zerbrochene Schallplatte",
    "einen unleserlichen Brief eines vorherigen Besuchers",
    "eine Botschaft vom Weihnachtsmann (er wünscht alles Gute)",
    "das geworfene Handtuch",
    "einen Quadratmeter frisch gemähtes Gras",
    "ein Ticket zum Mond",
    "den Kristallschädel",
    "ein angenagtes Stück Seife",
    "eine 5,25-Zoll-Diskette",
    "Gold, Weihrauch und Myrrhe",
    "eine ganze Aloe-Vera-Pflanze im Topf",
    "eine tickende Taschenuhr",
    "eine Rolle Klebestreifen ohne findbaren Anfang",
    "ein altes Telefon mit Wählscheibe auf einem Silbertablett",
    "ein Stilleben aus Wachs",
    "die historischen Überreste einer kaum Licht spendenden Waltranfunsel",
    "eine überraschende Wendung der Dinge",
    "eine dramatische Intrige",
    "einen geheimnisvollen Schlüssel unter einer Speiseglocke",
    "einen Rücktrittsbrief des Papstes",
    "ein unlösbares Rätsel",
    "einen brennenden Dornbusch",
    "ein Fragment der Heiligen Lanze",
    "eine defekte Spieluhr",
    "eine auslaufende Schneekugel mit Sprung",
    "Sägespäne mit knuspriger Baumrinde",
    "eine gleißend helle Sonne",
    "ein ambitioniertes Trainingsprogramm",
    "einen straffen Tagesplan",
    "eine Freikarte für einen sich im Niedergang befindenden Zirkus",
    "einen blinden Handspiegel",
    "Dornröschens Spindel",
    "die Bremer Stadtmusikanten",
    "den Orden pour le Mérite",
    "eine billige Imitation vom Goldenen Vlies",
    "einen Rasenziegel",
    "eine Mütze Schlaf",
    "einen alten ledrigen linken Stiefel",
    "eine Büste von Karl Marx",
    "eine Mao-Bibel",
    "einen Hauch von Verachtung für die niederen Dinge im Leben",
    "ein Brief eines gemeinsamen Feindes",
    "eine Warnung",
    "die Totenmaske des Tutanchamun",
    "einen Brief von Hogwarts in grüner Tinte",
    "einen verrückten Lodenfreak",
    "einen lang verschollenen Kindheitsfreund",
    "drei schimmernde Heilkristalle",
    "das Antlitz der Fata Morgana",
    "einen dreckigen Deal",
    "ein einschneidendes Erfolgserlebnis",
    "eine lebensgroße essbare Statue von Willy Wonka",
    "einen violetten Kaugummi, der jemanden in eine gigantische Blaubeere verwandeln wird",
    "eine Drachenfrucht und einen Drachen, mit dem du sie dir teilst",
    "volles Kommando über die Schlossküche und sieben Küchenhilfen",
    "einen Korb voll Petrischalen mit Nougat aus dem Lebensmittellabor",
    "einen Zahnstocher zum coolen Drauf-Rumkauen vorm Saloon",
    "die tickende Uhr der Ungeduld",
    "das schrille Geräusch eines Buzzers",
    "einen Tagessatz Löffel",
    "einen Kochlöffel",
    "einen Bezoar",
    "einen billigen Sparschäler",
    "eine Handvoll Kiefernnadeln für den Winterschlaf",
    "einen guten Anwalt",
    "eine Wagenladung Energie",
    "hellstrahlende Bewunderung",
    "dreißig sortierte Fäden zur Kontrollübernahme",
    "glitzernden Konfetti-Regen",
    "einen erwartungsvollen Blick",
    "zwei Würfel im Fünfer-Pasch",
    "drei Würfel im Sechser-Pasch",
    "eine aufgeschlagene Bibel",
    "einen lobenden Blick",
    "eine Prise Lieblichkeit",
    "einen fairen Punkt",
    "einen gutmütigen Klaps auf die Schulter",
    "eine Brille mit höherer Sehstärke",
    "ein lebendes Lama, das nun ein neuer Freund sein wird",
    "einen Teich und eine Angel",
    "einen schwebenden Heiligenschein",
    "einen Hut mit einer Krähe darauf",
    "einen Wink mit dem Zaunpfahl",
    "eine schwere Konzertharfe",
    "ein kompliziertes Brettspiel mit Anleitung",
    "ein kompliziertes Brettspiel ohne Anleitung",
    "eine Tauchtour an einem wunderschön erhaltenen Korallen-Riff",
    "die Sichtung eines vierhundert Jahre alten Grönland-Hais",
    "eine verblichene Schatzkarte zum nächsten Piratenschatz",
    "ein Flugticket zum Bermudadreieck",
    "einen Fluchtwagen mit quietschenden Reifen",
    "eine Einladung zu einem royalen Bankett",
    "zwei Tickets für Parkettplätze in der Semperoper",
    "zwei Tickets für Rangplätze in der Semperoper",
    "die Empfehlung, mal einen komplett freien Tag zu nehmen",
    "ein Krönchen und ein Zepter",
    "ein groß angelegtes Ablenkungsmanöver",
    "drei Dinosaurierbabys, die dir nun überallhin folgen",
    "einen Neon-Minigolfplatz mit Quallen-Ästhetik",
    "ein filigranes Opernglas",
    "eine Herde zutraulicher Capybaras und eine von ihnen adoptierte orange Katze",
    "einen spezialgelagerten Sonderfall",
    "einen Rolls-Royce mit britischem Chauffeur",
    "frisch geerntete Spinnenweben",
    "einen Escape-Room im Stil der 1920er",
    "die Antwort zu all deinen Sorgen",
    "einen Verwandlungszauber, der dich einen Tag lang das Leben als Qualle genießen lassen wird",
    "frisch gepressten Humor",
    "ein gutes Argument",
    "eine edle Teeparty für drei Stofftiere und einen einladend zurückgeschobenen Mini-Stuhl",
    "die aktuelle Ausgabe der Rocky Beach Today",
    "die neueste Ausgabe des Tagespropheten – natürlich per Eulenpost geliefert",
    "einen purpurnen Schal – denn Purpur bietet Schutz, müsst ihr wissen",
    "einen Nimbus 2000",
    "einen Zauberstab",
    "einen echten Goldenen Schnatz",
    "ein richtiges echtes Elbenseil",
    "einen Tarnumhang",
    "einen Lichtblick",
    "eine Diagnose deiner Wahl",
    "einen Mynah, der fortan alles nachsprechen wird, was du sagst",
    "eine Schatzkiste",
    "eine haarige Angelegenheit",
    "eine Schaufel Schnee",
    "einen wunderschönen viktorianischen Sonnenschirm mit edler Spitze",
    "einen robusten Regenschirm",
    "einen ausgezeichneten Ratschlag",
    "einen enthusiastischen Radschlag",
    "Prävention",
    "eine vorbeugende Maßnahme",
    "eine Knoblauch-Girlande zur Abwehr etwaiger Vampirbesucher",
    "einen Gong, der zu Tische ruft",
    "eine Handvoll Sand vom Sandmann – für süße Träume",
    "einen knuddeligen Hummer in einem riesigen, artgerechten Aquarium",
    "eine kostenlose Fahrt in Mortons schwarzem Rolls-Royce mit goldenen Beschlägen",
    "Respekt und Anerkennung",
    "ein stattliches Exemplar einer Mimbulus Mimbeltonia, die du nur sanft berühren solltest",
    "eine graue, seltsam stumpf wirkende Kette mit 48 Geisterperlen",
    "die peitschende Weide, die in deiner Gegenwart zur sanftmütigen Weide wird",
    "einen plätschernden Bach zum Planschen",
    "eine abgelehnte Petition",
    "einen auslaufenden Kautschukbaum",
    "einen Teller Empörung",
    "eine erholsame Pause",
    "eine sportliche Dehnungseinheit",
    "eine den Kreislauf ankurbelnde Trainingseinheit",
    "einen kreislaufstärkenden Saunaaufguss mit Eukalyptusöl",
    "Friede-Freude-Eierkuchen",
    "eine Handvoll Sonnencreme mit Lichtschutzfaktor 50",
    "eine Sonnenbrille",
    "eine flauschig-warme Kuscheldecke",
    "ein Trostpflaster",
    "geräuschreduzierende Kopfhörer",
    "eine heiße Dusche",
    "eine kalte Dusche",
    "ein paar Sonnenstrahlen",
    "eine schicke Schürze",
    "ein Pflaster",
    "ein paar Ohrenstöpsel",
    "eine Badekappe",
    "Schwimmflügel",
    "einen privaten Whirlpool",
    "einen überdachten Swimmingpool",
    "einen Infinity Pool fürs Training",
    "eine Sonnenliege",
    "eine Sonnenliege im Halbschatten",
    "eine im Wind wehende Ironie-Fahne",
    "einen Hoodie zum Verstecken",
    "den Orden des Merlins, 1. Klasse",
    "die Medaille für besondere Verdienste für den Chat",
]
