getraenkegoodones = [
    "einen Kaffee in einer Tasse aus blauem Porzellan",
    "eine Limonade in einem Cocktailglas mit Schirmchen",
    "einen Kakao in einer großen lila Tasse mit Löffel",
    "einen losen Tee in einem Gaiwan",
    "eine Cola mit einer Scheibe Zitrone in einem Glas mit Schirmchen",
    "kaltes Wasser",
    "kalten selbstgemachten Eistee",
    "frischen Mate in einem Kürbis mit einem verschnörkelten Strohhalm",
    "eine Flasche Club Mate",
    "einen frisch gepressten Apfelsaft",
    "einen frisch gepressten Traubensaft",
    "einen Kiwismoothie",
    "einen frisch gepressten Orangensaft",
    "einen Coconut Kiss in einem hohen Cocktailglas mit einer Scheibe Ananas am Rand",
    "ein Glas Milch",
    "einen Erdbeersmoothie",
    "einen Latte Macchiato mit einem Keks neben der Tasse",
    "eine Tasse heiße Schokolade aus Schokostückchen",
    "einen Mango-Melone-Smoothie",
    "ein Glas feinster Hoffnung",
    "einen frischen Pfefferminztee",
    "eine Eisschokolade mit Sahne",
    "einen Eiskaffee mit Sahne",
    "einen kalten Milchshake mit deinem Lieblingseis",
    "eine kalte Afri Cola",
    "einen Sojamilch-Milchkaffee mit einem Keks neben der Tasse",
    "einen Soja Latte Macchiato mit einem Keks neben der Tasse",
    "einen Blaubeersmoothie",
    "ein kaltes Spezi mit einer Scheibe Zitrone am Rand",
    "eine Karaffe kaltes Sprudelwasser",
    "einen großen Becher Kirsch-Banane-Nektar",
    "eine Flasche Mio Mio Mate",
    "eine Fritz!Cola",
    "eine Sprite mit Zitrone am Glas",
    "eine Fanta mit Orange am Glas",
    "ein leckeres Wasser",
    "ein edles Glas Kokosnussmilch",
    "eine Tasse lauwarmen Sencha",
    "ein Glas Chai Latte mit Sojamilch",
    "ein Tässchen kalten Sencha",
    "einen Cappuccino mit einem Keks neben der Tasse",
    "eine Tasse Cashew-Milch mit einem Schokokeks neben der Tasse",
    "eine Karaffe Hoffnung",
    "ein Glas Zuversicht",
    "eine Flasche Paulaner Spezi",
    "eine edle Tasse Soja-Kakao",
    "eine Flasche Bionade Holunder",
    "einen eiskalten Tereré",
    "einen kalt gezogenen grünen Tee",
    "eine edle Tasse frischen Kaffee mit Sojamilch",
    "ein Wasser in einem Glas mit einem schönen Schirmchen",
    "einen geschäumten Matcha in einer Teeschale",
    "ein verziertes Glas mit kalter Hafermilchschokolade",
    "einen frisch aufgeschlagenen Matcha in einer Teeschale",
    "eine Tasse Glück in einer großen Tasse mit Füchsen drauf",
    "einen Bubble Tea in einem verschnörkelten Glas mit großem Strohhalm",
    "ein Glas kalten Rooibos Tee mit Vanille verfeinert",
    "eine bunt karierte Tasse Kaffee",
    "einen Rainbow Cocktail in einem hohen Glas mit Schirmchen",
    "eine Apfelschorle mit frisch gepresstem Apfelsaft",
    "eine bunt gestreifte Tasse Tee",
    "ein Stilglas mit alkoholfreiem Sekt",
    "ein Glas mit erfrischend sprudelndem SchwipSchwap",
    "einen hellblauen Slushie mit Strohhalm",
    "die empfohlene tägliche Menge von 100 ml Cranberrysaft",
    "eine Buddel aufwendig hergestellten Granatapfelsaft",
    "ein Glas sprudelnde Rhabarberschorle",
    "ein Glas eisgekühlte Pfirsichschorle",
    "eine Tasse Matcha Latte",
    "eine Kanne koffeinfreien Kaffee und Zucker",
    "eine Virgin Piña Colada mit Ananas am Spieß darin",
    "ein Glas Lavendel-Limonade",
    "eine Karaffe Basilikum-Limonade",
    "selbst hergestellten Birnensaft",
    "einen erfrischenden Pfefferminz-Eistee",
    "selbst gemahlene Cashewmilch",
    "frisches Ingwerwasser",
    "eine Thermosflasche mit heißem Kamillentee",
    "eine Thermosflasche mit heißem Fencheltee",
    "eine Tasse Fenchel-Anis-Kümmel-Tee mit Honig",
    "einen frisch gebrühten Chociato",
    "eine Tasse pudrigen Chococino mit einem winzigen Keks",
    "eine entspannte Tasse Tee auf einer kuscheligen Fensterbank, während es draußen regnet",
    "einen Schluck Schokoladenmilch in einem knackigen Schokoladenbecherchen",
    "ein eiskaltes Matcha-Minz-Getränk",
    "eine heiße Tasse After-Eight-Kakao",
    "einen schweren Kristalldekanter mit edelstem Apfelsaft",
    "einen eiskalten Matcha-Tee mit Zitrone",
    "ein Glas eisgekühlten Johannisbeersaft",
    "einen fruchtigen Smoothie",
    "eine Tasse Kamillentee",
    "dreimal Kakao Spezial mit Vanillearoma",
    "einen Schluck echtes Wasser",
    "eine ganze Kanne Fenchel-Anis-Kümmel-Tee",
    "eine frisch aufgebrühte Tasse Kaffee mit Hafermilch",
    "ein Glas Heidelbeersaft",
    "heißen Holunderbeersaft",
    "einen wohltuenden Kräutertee",
    "eine Karaffe köstlichen Himbeersaft",
    "einen triumphierenden Shot Apfelsaft",
    "einen grellgrünen Smoothie mit extra vielen Vitaminen",
    "eine verzierte Porzellantasse Fine English Breakfast Tea",
    "eine Karaffe Wasser mit Gurkenscheiben",
    "eine Karaffe Wasser mit Ingwerstückchen",
    "eine Karaffe Wasser mit Limettenscheiben",
    "Frühstückssaft",
    "eine Karaffe Cola mit Zitronenscheiben und Eiswürfeln",
    "ein großes Glas Cola-Orange",
    "frischen Pfirsich-Eistee",
    "einen eiskalten Orangen-Milchshake",
    "ein perfekt zubereitetes Tässlein Kaffee",
    "einen kräutrigen Nachtrunk in einem winzigen Gläschen",
    "einen wohligen Nachttrunk aus heißer Milch mit Honig",
    "Limonade mit Eis",
    "Kürbissaft",
]
