icecream = [
    "drei Kugeln Schokoladeneis",
    "eine Tüte Stracciatellaeis",
    "einen Becher Himbeereis",
    "ein Schälchen Mango-Erdbeer-Eis",
    "ein Schälchen Heidelbeer-Pfirsich-Eis",
    "ein Wassermeloneneis am Stiel",
    "eine Tüte Erdbeereis",
    "Erdbeereis mit frischen Erdbeeren",
    "zwei Kugeln Bananeneis",
    "einen Becher Joghurteis",
    "6 Kugeln Heidelbeereis in einer glutenfreien Tüte",
    "Erdbeer-Joghurt-Eis mit bunten Streuseln",
    "ein Kokoseis",
    "einen Eimer Schlumpfeis",
    "eine Kugel Vanilleeis",
    "ein Pfefferminzeis mit zwei Schokotäfelchen",
    "ein laktosefreies Karamelleis",
    "eine Tüte Pistazieneis",
    "ein Apfelsorbet",
    "ein Zitronensorbet",
    "viel Mangosorbet",
    "ein Melonensorbet",
    "ein Waldmeistersorbet",
    "ein Waldbeersorbet",
    "ein Mango-Himbeereis",
    "ein Banane-Heidelbeereis",
    "einen Bananensplit",
    "einen Nussbecher",
    "ein Biene-Maja-Eis",
    "einen Erdbeerbecher",
    "Frozen-Yoghurt mit Früchten der Saison",
    "einen erfrischenden Früchtebecher",
    "Frozen-Yoghurt mit Streuseln",
    "einen Schokobecher mit Schokosoße",
    "einen Rocher-Becher",
    "ein Capri",
    "einen Raffaelo-Becher",
    "5 Eispralinen",
    "ein Calippo",
    "ein Big-Sandwich",
    "ein Mini-Milk",
    "ein fröhlich knisterndes Kaktus-Eis",
    "ein Nucki Nuss",
    "ein Cornetto Schoko vegan",
    "ein Cornetto Schoko",
    "ein Cornetto Erdbeer vegan",
    "ein Cornetto Erdbeer",
    "Spaghettieis",
    "einen Haufen Eiswürfel",
    "ein Bum Bum",
    "ein warmes Kirscheis",
    "ein Eis",
    "ein Kaffeeeis",
    "einen Apfelslushy",
    "einen Kiwislushy",
    "einen Kirschslushy",
    "einen Eiszapfenslushy",
    "ein Softeis",
    "ein Durianeis am Stiel",
    "ein Himbeereis",
    "einen Eiskaffee",
    "einen gefrorenen Keks",
    "eine Packung Ben and Jerry's Cookie Dough",
    "ein Walnusseis",
    "ein Pistazieneis",
    "ein Haselnusseis",
    "ein Schwimmbecken voll Brombeereis",
    "ein Glas Wasser mit binären Eiswürfeln",
    "einen Coppa del Nonno",
    "ein veganes Zitroneneis",
    "ein grünes Wassereis",
    "ein Jolly",
    "ein Twinni",
    "ein Tschisi",
    "einen Plattfuß",
    "ein Supertwister",
    "ein Twister",
    "ein Fruchtzwerg-Eis am Stiel",
    "einen Honigmeloneneisbecher",
    "ein Honigmeloneneis",
    "ein Schoko Waffeleis vegan von Valsoia",
    "ein Durianeis am Stiel",
    "ein billiges Zitroneneis am Stiel"
    "eine Schale Regenbogeneis mit Kaugummigeschmack",
    "einen großen Karamelleisbecher",
    "einen Teller Spaghettieis mit Erdbeersoße",
    "ein dänisches Eis mit knackiger Schokohülle",
    "Eiscreme mit Waldmeistergeschmack",
    "eine Waffel mit Schokoladen-Minz-Eiscreme",
    "eine Schale Frozen Joghurt mit zehn verschiedenen Toppings",
    "drei Kugeln Cookies`n-Cream-Eis",
    "eine ganze Packung Banana-Split und einen Löffel",
    "ein Himbeereis mit weißer Schokoladenhülle",
    "Mokka-Eiscreme mit einem klitzebisschen Pistazie",
    "einen Tuppen Eiscreme und einen Löffel",
    "Matcha-Eiscreme am Stiel",
    "ein Minz-Eis im Schokomantel",
    "ein köstliches Eis aus Mandarine und Quark",
    "einen leckeren Eisbecher mit Birne und Krokant",
    "einen Tupfen Mohn-Marzipan-Eis",
    "einen Tupfen Triple Chocolate Extra Super Fudge",
    "Milcheis mit Haselnuss",
    "Milcheis mit Zimt",
    "Nougateis am Stiel",
    "Pflaumensorbet mit Teigstreuseln",
    "frisches Wassermelonensorbet",
    "ein hochwertiges Sorbet aus gelber Kiwi",
    "Frozen Joghurt mit kühlen Gummibärchen",
    "eine besondere Kreation aus Passionsfrucht und Krokant",
    "ein ummandeltes Nusseis mit zwei Stielen",
    "einen fruchtigen Joghurt-Eiscreme-Shake",
    "ein dreifaches Eiscreme-Sandwich",
    "einen Triple Gooberberry Sunrise mit ganzen drei Bananen",
    "einen Tupfen vegane Lupineneiscreme",
    "drei Kugeln Schoko-Lupineneis",
    "eine Kugel Sorbet in jeder Farbe des Regenbogens",
    "eine Eistüte mit drei prekär balancierenden Kugeln",
    "einen bimmelnden Eiscreme-Truck und ein paar Münzen",
    "eine eiskalte Belohnung",
    "zwei Snickers-Eiscreme-Riegel"
]
