snacks = [
    "eine handvoll Salzbrezeln",
    "ein Schälchen Chips",
    "5 M&Ms",
    "ein Päckchen gesalzene Nüsse",
    "ein paar Apfelschnitze",
    "eine Tüte salziges Popcorn",
    "ein Täfelchen Schokolade",
    "ein kleines Stück Käsekuchen",
    "ein kleines Stück Kuchen nach Wahl",
    "ein kleines Schälchen Schokoladen Keksi",
    "eine Hand voll Trockenfrüchte",
    "einen gesunden Riegel",
    "eine Tüte Luft",
    "5 Schokobons",
    "eine Schale Nachos",
    "einen Kinderriegel",
    "eine schwarze Lindor Schokokugel",
    "eine Kino Portion süßes Popcorn",
    "eine Schale Wasabi Erdnüsse",
    "eine kleine Schale Pistazien",
    "eine Handvoll Macadamia-Nüsse",
    "ein Glaß voller Salzstangen",
    "eine Tafel Schokolade",
    "eine Tüte Chips",
    "ein Snickers",
    "einen Mars-Riegel",
    "eine Handvoll Gummibärchen",
    "eine Schale mit Kartoffelchips",
    "ein hart gekochtes Ei",
    "vier Pralinen mit Nougatfüllung",
    "einen fruchtigen Lolli",
    "einen Blaubeermuffin mit Sahne",
    "einen Erdnussbutterriegel",
    "eine Schachtel Lebkuchen",
    "eine Packung Choco-Fresh",
    "fein geschnittene Karottenstückchen mit laktosefreiem Frischkäse",
    "eine Tüte Maiswaffeln",
    "eine Handvoll Studentenfutter",
    "ein Schüsselchen Studentenfutter ohne Rosinen",
    "eine Handvoll Knabbersoja",
    "eine Schachtel Pralinen",
    "ein Dreierpack Ahoj-Brause",
    "eine Handvoll rohe Mandeln",
    "drei klebrige Ricola-Hustenbonbons",
    "eine Auswahl an Käsesorten mit Weintrauben",
    "ein Stück glasierten Zitronenkuchen",
    "einen hübsch verzierten Cupcake",
    "einen drolligen Cake-Pop",
    "einen Donut mit Ahornsirup",
    "einen Spieß frisch gebackener Kartoffelchips mit Salz und Essig",
    "eine Handvoll getrocknete Früchte",
    "Bertie-Botts-Bohnen in den sonderbarsten Geschmacksrichtungen",
    "drei brodelnde Kesselküchlein",
    "eine Schale festklebender Bonbons aus Omas Schrank",
    "eine Packung Schokofrösche",
    "ein Hörnchen vom nächsten Bäcker",
    "eine Schale Nachos mit Käsesoße",
    "eine Tüte süßes Popcorn",
    "eine Tüte salziges Popcorn",
    "einen Kaugummi mit Drei-Gänge-Menü-Geschmack",
    "süße Siruptörtchen",
    "eine große Wolke Zuckerwatte",
    "ein Blech Rosinenfladen",
    "drei Schaumküsse mit verschiedenen Geschmacksrichtungen",
    "eine Tüte Chiasamen zum Knabbern",
    "eine Familienpackung Toffifee",
    "eine Schale Süßigkeiten von letztem Halloween",
    "kandierte Früchte am Stiel",
    "ein Päckchen Gummibärchen für die Tapferkeit",
    "eine plattgedrückte Mozartkugel",
    "einen einzelnen karamellisierten Marshmallow",
    "ein Schokoladentörtchen mit geschmolzenem Kern",
    "eine Partypackung Salzstangen",
    "einige frittierte Quarkbällchen",
    "eine Tüte Mutzen vom Weihnachtsmarkt",
    "eine Schale gesalzener Chips mit Salsa-Dip",
    "zwei glasierte Donuts",
    "eine Packung Minz-Tic-Tacs",
    "einen winzigen Muffin, der nicht so weich ist, wie er aussieht",
    "eine angebrochene Packung Oreos",
    "die letzte Packung Schokolade",
    "eine Packung knusprige Käsestangen",
    "eine ganze Zitrone",
    "eine Schale Chiapudding mit Mango",
    "eine weiche Birne",
    "eine einzelne Walnuss",
    "gebackene Bananenbällchen mit Honig",
    "eine Schale geriebenen Gouda",
    "drei einzelne Kartoffelchips",
    "eine Packung Kartoffelchips mit BBQ-Geschmack",
    "eine Auswahl verschiedenster Macarons",
    "ein Stück knusprig-schokoladigen kalten Hund",
    "drei bunte Dango am Stiel",
    "einige mit v-Speck umrollte Datteln",
    "ein überdimensional großes Nougatkissen",
    "türkischen Honig in einer edel verzierten Schale",
    "eine Tafel vegane Schokolade",
    "einen Laib Marzipanbrot",
    "eine Packung Wikingerröllchen",
    "einige harte Salzkaramell-Bonbons",
    "Nougat in Form von Meeresfrüchten",
    "eine XXL-Packung Merci",
    "ein paar Trüffelpralinen",
    "gepudertes Kokos-Mochi",
    "zwei gepuderte Vanille-Mochi",
    "drei klebrige Mango-Mochi",
    "eine vakuumierte Packung mehlig-süßer Esskastanien",
    "ein paar frische, heiße Maronen",
    "eine Handvoll Sonnenblumenkerne",
    "Käse-Schinken-Trauben-Spieße, symmetrisch arrangiert",
    "drei winzige Mini-Gugelhupfe mit Stracciatella-Geschmack",
    "eine Schokoladenorange",
    "eine edle Praline mit Tomatensuppe-Geschmack",
    "zwei pastellgrüne Pistazien-Macarons",
    "einen pink glänzenden Himbeermacaron mit einem Hauch Rosenwasser",
    "eine nussige Marzipanpraline",
    "eine cremige Tiramisu-Praline mit Mascarpone und Espressopulver",
    "einen hellen Macaron mit einer Luxusfüllung aus weißem Trüffel",
    "einen Mini-Gugelhupf mit Haselnuss-Schokoladen-Füllung",
    "kleine Törtchen, gefüllt mit zitronigem Lemon Curd",
    "ein süßes Küchlein mit Smartie-Füllung",
    "eine Handvoll ausschließlich gelber Smarties",
    "eine Schale ungesalzener Erdnüsse",
    "ein Schälchen mit getrockneten Cranberries",
    "eine Portion Erdnussflips und einen guten Film",
    "zwei Kristallschüsseln, eine mit aromatisierten Pistazien, eine für die Schalen",
    "eine der Länge nach halbierte Karotte mit einer gefalteten Käsescheibe dazwischen",
    "sternenförmige Melonenstücke",
    "ein paar Apfelstreifen mit Erdnussbutter",
    "schokoladige Reiswaffeln",
    "eine Schale mit Sesam bestreuter Edamame",
    "eine Gemüsefigur mit Sellerie-Beinchen",
    "eine Handvoll Salbeiblätter zum Schnuppern",
    "eine Handvoll getrockneter Nelken zum Drauf-Rumkauen",
    "ein Bonbon aus Kirschgelee mit Banane und süßer Sahne",
    "ein Bonbon aus bitterer Schokolade, Mandelcreme und einem Hauch Pfefferminz",
    "ein Bonbon mit echtem Zitronenaroma, Haselnuss und dünner Krokantkruste",
    "eine klein geschnittene Banane",
    "Apfelringe",
    "ein paar Birnenbällchen aus dem Glas",
    "eine Handvoll Johannisbeeren",
    "frisch gepflückte Wildheidelbeeren",
    "drei Gläser Oliven",
    "ein winziges Stückchen Lembas-Brot … das reicht für einen ganzen Tag",
    "einen High-Protein-Riegel",
    "eine Stange Porree",
    "eine Wochenration Studentenfutter",
    "eine Prise Ursteinsalz aus dem Himalaya",
    "eine überreife Banane, dick mit Erdnussbutter bestrichen",
    "ein harmlos aussehendes Bonbon aus Weasleys' Wizard Wheezes",
    "Schokolade gegen Dementoren",
    "Eicheln und Zirbelnüsse",
    "eine Handvoll vegane Fruchtgummis",
    "Tortilla-Chips mit Tacogeschmack",
    "Tortilla-Chips mit Käsegeschmack, dazu Käsedip",
    "Tortilla-Chips mit Salsa",
    "knusprige Chips mit Salz und Essig",
    "einen Esslöffel geriebenen Cheddar",
    "herrlich duftende gebrannte Mandeln",
    "einen sagenumwobenen Seetang-Riegel",
    "ein gläsernes Schüsselchen mit schokoladenummantelten Rosinen",
    "eine Tüte voll verräterisch knackender Gemüsechips",
    "einen Räuberriegel-Proviant für lange Ausflüge",
    "eine Regenbogen-Zuckerwatte",
    "einen kandierten Apfel",
    "einen Berg Schokoraspeln",
    "ein Schüsselchen geraffelter Äpfel",
    "ein Knabbermöhrchen",
    "ein paar herrliche Zimtsterne",
    "eine raschelnde Packung Knuspermüsli und eine Schale",
    "einen prachtvollen Zuckerfederkiel",
    "einen Lakritz-Zauberstab",
    "Zahnweiß-Pfefferminzlakritze",
    "eine Handvoll alte Erdnüsse",
    "eine Wagenladung voll Spritzgebäck",
    "Schlagsahne direkt aus der Sprühdose",
    "eine übergroße Erdbeere mit Sahnehäubchen",
    "ein ausgeplündertes Überraschungsei",
    "eine überreife Banane mit braunen Stellen",
    "ein paar Stücke klebrigen Lokum",
]
