snacks = [
    "eine handvoll Salzbrezeln",
    "ein Schälchen Chips",
    "fünf M&Ms",
    "ein Päckchen gesalzene Nüsse",
    "ein paar Apfelschnitze",
    "ein Täfelchen Schokolade",
    "ein kleines Stück Käsekuchen",
    "ein kleines Stück Kuchen nach Wahl",
    "ein kleines Schälchen Schokoladen Keksi",
    "eine Hand voll Trockenfrüchte",
    "einen gesunden Riegel",
    "eine Tüte Luft",
    "fünf Schokobons",
    "eine Schale Nachos",
    "einen Kinderriegel",
    "eine schwarze Lindor Schokokugel",
    "eine Kino Portion süßes Popcorn",
    "eine Schale Wasabi Erdnüsse",
    "eine kleine Schale Pistazien",
    "eine Handvoll Macadamia-Nüsse",
    "ein Glaß voller Salzstangen",
    "eine Tafel Schokolade",
    "eine Tüte Chips",
    "ein Snickers",
    "einen Mars-Riegel",
    "eine Handvoll Gummibärchen",
    "eine Schale mit Kartoffelchips",
    "ein hart gekochtes Ei",
    "vier Pralinen mit Nougatfüllung",
    "einen fruchtigen Lolli",
    "einen Blaubeermuffin mit Sahne",
    "einen Erdnussbutterriegel",
    "eine Schachtel Lebkuchen",
    "eine Packung Choco-Fresh",
    "fein geschnittene Karottenstückchen mit laktosefreiem Frischkäse",
    "eine Tüte Maiswaffeln",
    "eine Handvoll Studentenfutter",
    "ein Schüsselchen Studentenfutter ohne Rosinen",
    "eine Handvoll Knabbersoja",
    "eine Schachtel Pralinen",
    "ein Dreierpack Ahoj-Brause",
    "eine Handvoll rohe Mandeln",
    "drei klebrige Ricola-Hustenbonbons",
    "eine Auswahl an Käsesorten mit Weintrauben",
    "ein Stück glasierten Zitronenkuchen",
    "einen hübsch verzierten Cupcake",
    "einen drolligen Cake-Pop",
    "einen Donut mit Ahornsirup",
    "einen Spieß frisch gebackener Kartoffelchips mit Salz und Essig",
    "eine Handvoll getrocknete Früchte",
    "Bertie-Botts-Bohnen in den sonderbarsten Geschmacksrichtungen",
    "drei brodelnde Kesselküchlein",
    "eine Schale festklebender Bonbons aus Omas Schrank",
    "eine Packung Schokofrösche",
    "ein Hörnchen vom nächsten Bäcker",
    "eine Schale Nachos mit Käsesoße",
    "eine Tüte süßes Popcorn",
    "eine Tüte salziges Popcorn",
    "einen Kaugummi mit Drei-Gänge-Menü-Geschmack",
    "süße Siruptörtchen",
    "eine große Wolke Zuckerwatte",
    "ein Blech Rosinenfladen",
    "drei Schaumküsse mit verschiedenen Geschmacksrichtungen",
    "eine Tüte Chiasamen zum Knabbern",
    "eine Familienpackung Toffifee",
    "eine Schale Süßigkeiten von letztem Halloween",
    "kandierte Früchte am Stiel",
    "ein Päckchen Gummibärchen für die Tapferkeit",
    "eine plattgedrückte Mozartkugel",
    "einen einzelnen karamellisierten Marshmallow",
    "ein Schokoladentörtchen mit geschmolzenem Kern",
    "eine Partypackung Salzstangen",
    "einige frittierte Quarkbällchen",
    "eine Tüte Mutzen vom Weihnachtsmarkt",
    "eine Schale gesalzener Chips mit Salsa-Dip",
    "zwei glasierte Donuts",
    "eine Packung Minz-Tic-Tacs",
    "einen winzigen Muffin, der nicht so weich ist, wie er aussieht",
    "eine angebrochene Packung Oreos",
    "die letzte Packung Schokolade",
    "eine Packung knusprige Käsestangen",
    "eine ganze Zitrone",
    "eine Schale Chiapudding mit Mango",
    "eine weiche Birne",
    "eine einzelne Walnuss",
    "gebackene Bananenbällchen mit Honig",
    "eine Schale geriebenen Gouda",
    "drei einzelne Kartoffelchips",
    "eine Packung Kartoffelchips mit BBQ-Geschmack",
    "eine Auswahl verschiedenster Macarons",
    "ein Stück knusprig-schokoladigen kalten Hund",
    "drei bunte Dango am Stiel",
    "einige mit v-Speck umrollte Datteln",
    "ein überdimensional großes Nougatkissen",
    "türkischen Honig in einer edel verzierten Schale",
    "eine Tafel vegane Schokolade",
    "einen Laib Marzipanbrot",
    "eine Packung Wikingerröllchen",
    "einige harte Salzkaramell-Bonbons",
    "Nougat in Form von Meeresfrüchten",
    "eine XXL-Packung Merci",
    "ein paar Trüffelpralinen",
    "gepudertes Kokos-Mochi",
    "zwei gepuderte Vanille-Mochi",
    "drei klebrige Mango-Mochi",
    "eine vakuumierte Packung mehlig-süßer Esskastanien",
    "ein paar frische, heiße Maronen",
    "eine Handvoll Sonnenblumenkerne",
    "Käse-Schinken-Trauben-Spieße, symmetrisch arrangiert",
    "drei winzige Mini-Gugelhupfe mit Stracciatella-Geschmack",
    "eine Schokoladenorange",
    "eine edle Praline mit Tomatensuppe-Geschmack",
    "zwei pastellgrüne Pistazien-Macarons",
    "einen pink glänzenden Himbeermacaron mit einem Hauch Rosenwasser",
    "eine nussige Marzipanpraline",
    "eine cremige Tiramisu-Praline mit Mascarpone und Espressopulver",
    "einen hellen Macaron mit einer Luxusfüllung aus weißem Trüffel",
    "einen Mini-Gugelhupf mit Haselnuss-Schokoladen-Füllung",
    "kleine Törtchen, gefüllt mit zitronigem Lemon Curd",
    "ein süßes Küchlein mit Smartie-Füllung",
    "eine Handvoll ausschließlich gelber Smarties",
    "eine Schale ungesalzener Erdnüsse",
    "ein Schälchen mit getrockneten Cranberries",
    "eine Portion Erdnussflips und einen guten Film",
    "zwei Kristallschüsseln, eine mit aromatisierten Pistazien, eine für die Schalen",
    "eine der Länge nach halbierte Karotte mit einer gefalteten Käsescheibe dazwischen",
    "sternenförmige Melonenstücke",
    "ein paar Apfelstreifen mit Erdnussbutter",
    "schokoladige Reiswaffeln",
    "eine Schale mit Sesam bestreuter Edamame",
    "eine Gemüsefigur mit Sellerie-Beinchen",
    "eine Handvoll Salbeiblätter zum Schnuppern",
    "eine Handvoll getrockneter Nelken zum Drauf-Rumkauen",
    "ein Bonbon aus Kirschgelee mit Banane und süßer Sahne",
    "ein Bonbon aus bitterer Schokolade, Mandelcreme und einem Hauch Pfefferminz",
    "ein Bonbon mit echtem Zitronenaroma, Haselnuss und dünner Krokantkruste",
    "eine klein geschnittene Banane",
    "Apfelringe",
    "ein paar Birnenbällchen aus dem Glas",
    "eine Handvoll Johannisbeeren",
    "frisch gepflückte Wildheidelbeeren",
    "drei Gläser Oliven",
    "ein winziges Stückchen Lembas-Brot … das reicht für einen ganzen Tag",
    "einen High-Protein-Riegel",
    "eine Stange Porree",
    "eine Wochenration Studentenfutter",
    "eine Prise Ursteinsalz aus dem Himalaya",
    "eine überreife Banane, dick mit Erdnussbutter bestrichen",
    "ein harmlos aussehendes Bonbon aus Weasleys' Wizard Wheezes",
    "Schokolade gegen Dementoren",
    "Eicheln und Zirbelnüsse",
    "eine Handvoll vegane Fruchtgummis",
    "Tortilla-Chips mit Tacogeschmack",
    "Tortilla-Chips mit Käsegeschmack, dazu Käsedip",
    "Tortilla-Chips mit Salsa",
    "knusprige Chips mit Salz und Essig",
    "einen Esslöffel geriebenen Cheddar",
    "herrlich duftende gebrannte Mandeln",
    "einen sagenumwobenen Seetang-Riegel",
    "ein gläsernes Schüsselchen mit schokoladenummantelten Rosinen",
    "eine Tüte voll verräterisch knackender Gemüsechips",
    "einen Räuberriegel-Proviant für lange Ausflüge",
    "eine Regenbogen-Zuckerwatte",
    "einen kandierten Apfel",
    "einen Berg Schokoraspeln",
    "ein Schüsselchen geraffelter Äpfel",
    "ein Knabbermöhrchen",
    "ein paar herrliche Zimtsterne",
    "eine raschelnde Packung Knuspermüsli und eine Schale",
    "einen prachtvollen Zuckerfederkiel",
    "einen Lakritz-Zauberstab",
    "Zahnweiß-Pfefferminzlakritze",
    "eine Handvoll alte Erdnüsse",
    "eine Wagenladung voll Spritzgebäck",
    "Schlagsahne direkt aus der Sprühdose",
    "eine übergroße Erdbeere mit Sahnehäubchen",
    "ein ausgeplündertes Überraschungsei",
    "eine überreife Banane mit braunen Stellen",
    "ein paar Stücke klebrigen Lokum",
    "eine Brezel",
    "einen sahnigen Schokopudding",
    "ein Schälchen Apfelmus",
    "eine Mango",
    "einen Teller getrocknete Jackfruchtstücke",
    "eine Waffel mit Puderzucker",
    "einen Eimer buntes Popcorn",
    "ein knuspriges Laugendreieck",
    "eine kleine Schale Honigpudding",
    "eine Schale liebevoll geschnittenes Obst",
    "eine schmackhafte Ingwerwurzel",
    "fischförmiges Gebäck mit roter Bohnenfüllung",
    "ein Stück frische Honigwabe",
    "kandierte Pomeloschale",
    "eine Schale Pudding mit echtem Sago",
    "Poffertjes mit Agavendicksaft und Früchten",
    "Poffertjes mit Butter und Puderzucker",
    "zwei Kokosnuss-Limetten-Törtchen",
    "zwei Schokoladen-Tarteletts mit frischer Minze",
    "eine Tupperdose mit einer Klappstulle",
    "eine Tupperdose mit einem Joghurt und einem klappernden Löffel",
    "zwei knusprige Churros mit Mango-Chili-Füllung",
    "zwei Churros mit überraschend türkiser Füllung",
    "ein kleines Bäumchen mit Schokoladenfrüchten",
    "einen Cocktailspieß, voll bestückt mit Sternfrucht und Physalis",
    "einen Cocktailspieß, voll bestückt mit Ananas",
    "ein Löffelchen Semmelbrösel",
    "ein saftiges Stück Pfirsich-Schmand-Kuchen",
    "einen mit Marshmallows überbackenen Brownie",
    "ein kleines Stück veganen Gewürzkuchen",
    "ein Stück englischen Teekuchen zum Tee",
    "zwei kleine Mango-Kokos-Törtchen",
    "ein Stückchen Kürbis-Apfelkuchen",
    "zwei Käsekuchen-Muffins",
    "einen Oreo-Muffin",
    "einen Espresso-Muffin mit Karamellfüllung",
    "ein Stückchen Maulwurfkuchen",
    "schokoladigen Tassenkuchen",
    "fruchtigen Tassenkuchen",
    "ein Stück Earl-Grey-Kugelhupf und dazu eine Tasse Schwarztee",
    "saftige Kuchenpralinen, angerichtet auf einer muschelförmigen Platte",
    "einen ganzen Strauß bunt verzierter Cake-Pops",
    "Low-Carb Hüttenkäsetaler",
    "Vollkorncracker mit Tomaten-Dip",
    "Salzcracker mit frischem Gurken-Dip",
    "duftende Knoblauchknoten",
    "gepuderte Dattel-Nuss-Bällchen",
    "Hirse auf dem Fensterbrett",
    "vegane Milchschnitten",
    "knusprige Brokkoli-Taler",
    "ein winziges Schüsselchen Polenta",
    "in Chiasamen gerollte Möhrenbällchen",
    "knusprige Veggie-Nuggets",
    "Himbeer-Schokoladen-Bissen",
    "ein Schälchen Kokoscreme mit Melone",
    "selbstgemachte Mandel-Müsli-Riegel",
    "gegrillte Birnenhälften mit Zitronenthymian",
    "vegane Tofu-Erdnuss-Sticks",
    "sizilianische Cannoli mit Ricotta, Pistazien und Schokostreuseln",
    "vier fluffige Birnenmuffins",
    "einen innovativen Tiramisu-Muffin",
]
